-- swap_hash_owners reserves each payment hash for either the established swap
-- roles or a composite refresh. Pay and receive may legitimately coexist for
-- one in-Ark transfer, while refresh must exclusively own both of its legs.
CREATE TABLE IF NOT EXISTS swap_hash_owners (
    payment_hash BLOB PRIMARY KEY,
    direction TEXT NOT NULL CHECK (direction IN ('standard', 'refresh'))
);

-- Preserve legitimate opposite-role pairs as one standard owner class.
INSERT INTO swap_hash_owners (payment_hash, direction)
SELECT payment_hash, 'standard' FROM pay_swaps
WHERE true
ON CONFLICT (payment_hash) DO NOTHING;

INSERT INTO swap_hash_owners (payment_hash, direction)
SELECT payment_hash, 'standard' FROM receive_swaps
WHERE true
ON CONFLICT (payment_hash) DO NOTHING;

-- Durable two-leg VTXO refresh sessions. A refresh keeps one client-owned
-- preimage across a client-funded input vHTLC and a newer server-funded output
-- vHTLC, so both legs must advance under one crash-safe state machine.
CREATE TABLE IF NOT EXISTS refresh_swaps (
    -- payment_hash is the shared hashlock and durable refresh identity.
    payment_hash BLOB PRIMARY KEY,

    -- preimage is generated by the client before any remote side effect and is
    -- retained for output claiming and daemon-owned unilateral recovery.
    preimage BLOB NOT NULL,

    -- amount_sat is the exact value expected in both vHTLC legs.
    amount_sat BIGINT NOT NULL,

    -- source_outpoint is the caller-selected managed VTXO used to fund the
    -- input leg. It is immutable across replay.
    source_outpoint TEXT NOT NULL,

    -- max_vtxo_age_blocks is the caller's immutable backing-batch age cap for
    -- the server-funded output leg and must be positive.
    max_vtxo_age_blocks BIGINT NOT NULL,

    -- state is the current client-side refresh FSM state name.
    state TEXT NOT NULL,

    -- state_version provides optimistic concurrency control across separately
    -- resumed foreground and background session objects.
    state_version BIGINT NOT NULL,

    -- expiry_unix is the server-provided input-funding deadline.
    expiry_unix BIGINT NOT NULL DEFAULT 0,

    -- client_pubkey serves as input sender and output receiver.
    client_pubkey BLOB NOT NULL,

    -- operator_pubkey is the Ark operator key used by both vHTLC policies.
    operator_pubkey BLOB NOT NULL,

    -- server_pubkey serves as input receiver and output sender.
    server_pubkey BLOB,

    -- settlement_type must remain "refresh" after negotiation.
    settlement_type TEXT NOT NULL DEFAULT '',

    input_refund_locktime BIGINT NOT NULL DEFAULT 0,
    input_unilateral_claim_delay BIGINT NOT NULL DEFAULT 0,
    input_unilateral_refund_delay BIGINT NOT NULL DEFAULT 0,
    input_unilateral_refund_without_receiver_delay BIGINT NOT NULL DEFAULT 0,
    input_vhtlc_pkscript BLOB,
    input_vhtlc_policy_template BLOB,
    input_vhtlc_outpoint TEXT NOT NULL DEFAULT '',
    input_vhtlc_amount BIGINT NOT NULL DEFAULT 0,
    funding_session_id TEXT NOT NULL DEFAULT '',

    -- The refund destination and recovery row are allocated before input
    -- funding, so a crash never leaves a funded first leg without recovery.
    input_refund_receive_pubkey BLOB NOT NULL,
    input_refund_receive_pkscript BLOB NOT NULL,
    input_refund_session_id TEXT NOT NULL DEFAULT '',
    input_refund_recovery_id TEXT NOT NULL DEFAULT '',

    output_sender_pubkey BLOB,
    output_refund_locktime BIGINT NOT NULL DEFAULT 0,
    output_unilateral_claim_delay BIGINT NOT NULL DEFAULT 0,
    output_unilateral_refund_delay BIGINT NOT NULL DEFAULT 0,
    output_unilateral_refund_without_receiver_delay BIGINT NOT NULL DEFAULT 0,
    output_vhtlc_pkscript BLOB,
    output_vhtlc_policy_template BLOB,
    output_vhtlc_outpoint TEXT NOT NULL DEFAULT '',
    output_vhtlc_amount BIGINT NOT NULL DEFAULT 0,

    -- These heights preserve the client-side evidence that the funded output
    -- met max_vtxo_age_blocks when it was accepted.
    output_observed_height BIGINT NOT NULL DEFAULT 0,
    output_created_height BIGINT NOT NULL DEFAULT 0,
    output_batch_expiry BIGINT NOT NULL DEFAULT 0,

    -- The mailbox cursor is cleared only after local persistence, mailbox ACK,
    -- and the signed server ACK all succeed.
    pending_htlc_ack_cursor BIGINT NOT NULL DEFAULT 0,

    output_claim_receive_pubkey BLOB NOT NULL,
    output_claim_receive_pkscript BLOB NOT NULL,
    output_claim_session_id TEXT NOT NULL DEFAULT '',
    output_claim_recovery_id TEXT NOT NULL DEFAULT '',

    -- input_claim_txid records the server spend that completed the exchange.
    input_claim_txid TEXT NOT NULL DEFAULT '',
    intervention_reason TEXT NOT NULL DEFAULT '',
    created_at_unix BIGINT NOT NULL,
    updated_at_unix BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_refresh_swaps_state
    ON refresh_swaps(state, updated_at_unix);
