// Code generated by protoc-gen-mailboxrpc. DO NOT EDIT.

package swaprpc

import (
	context "context"
	fmt "fmt"
	rpc "github.com/lightninglabs/wavelength/mailbox/rpc"
	proto "google.golang.org/protobuf/proto"
)

// SwapServiceMailboxClient is a typed mailbox RPC client for SwapService.
type SwapServiceMailboxClient struct {
	// C is the underlying RPC-over-mailbox runtime client.
	C rpc.RPCClient
}

// NewSwapServiceMailboxClient creates a typed mailbox client.
func NewSwapServiceMailboxClient(c rpc.RPCClient) *SwapServiceMailboxClient {
	return &SwapServiceMailboxClient{
		C: c,
	}
}

// SwapServiceMailboxServer is the mailbox server interface for SwapService.
type SwapServiceMailboxServer interface {
	// RequestChannelId handles RequestChannelId.
	RequestChannelId(ctx context.Context, req *RequestChannelIdRequest) (*RequestChannelIdResponse, error)
	// CreateInSwap handles CreateInSwap.
	CreateInSwap(ctx context.Context, req *CreateInSwapRequest) (*CreateInSwapResponse, error)
	// QuoteInSwap handles QuoteInSwap.
	QuoteInSwap(ctx context.Context, req *QuoteInSwapRequest) (*QuoteInSwapResponse, error)
	// CreateCredit handles CreateCredit.
	CreateCredit(ctx context.Context, req *CreateCreditRequest) (*CreateCreditResponse, error)
	// RedeemCredit handles RedeemCredit.
	RedeemCredit(ctx context.Context, req *RedeemCreditRequest) (*RedeemCreditResponse, error)
	// ListCredits handles ListCredits.
	ListCredits(ctx context.Context, req *ListCreditsRequest) (*ListCreditsResponse, error)
	// AuthorizeInSwapRefund handles AuthorizeInSwapRefund.
	AuthorizeInSwapRefund(ctx context.Context, req *AuthorizeInSwapRefundRequest) (*AuthorizeInSwapRefundResponse, error)
	// AcknowledgeOutSwapHtlc handles AcknowledgeOutSwapHtlc.
	AcknowledgeOutSwapHtlc(ctx context.Context, req *AcknowledgeOutSwapHtlcRequest) (*AcknowledgeOutSwapHtlcResponse, error)
	// SignInSwapForfeit handles SignInSwapForfeit.
	SignInSwapForfeit(ctx context.Context, req *SignInSwapForfeitRequest) (*SignInSwapForfeitResponse, error)
	// SubmitOutSwapForfeitSignature handles SubmitOutSwapForfeitSignature.
	SubmitOutSwapForfeitSignature(ctx context.Context, req *SubmitOutSwapForfeitSignatureRequest) (*SubmitOutSwapForfeitSignatureResponse, error)
}

// RegisterSwapServiceMailboxServer registers handlers for SwapService.
func RegisterSwapServiceMailboxServer(r rpc.Router, impl SwapServiceMailboxServer) {
	r.Handle("swaprpc.SwapService", "RequestChannelId", func() proto.Message {
		return &RequestChannelIdRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*RequestChannelIdRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.RequestChannelId(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "CreateInSwap", func() proto.Message {
		return &CreateInSwapRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*CreateInSwapRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.CreateInSwap(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "QuoteInSwap", func() proto.Message {
		return &QuoteInSwapRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*QuoteInSwapRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.QuoteInSwap(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "CreateCredit", func() proto.Message {
		return &CreateCreditRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*CreateCreditRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.CreateCredit(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "RedeemCredit", func() proto.Message {
		return &RedeemCreditRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*RedeemCreditRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.RedeemCredit(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "ListCredits", func() proto.Message {
		return &ListCreditsRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ListCreditsRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ListCredits(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "AuthorizeInSwapRefund", func() proto.Message {
		return &AuthorizeInSwapRefundRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*AuthorizeInSwapRefundRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.AuthorizeInSwapRefund(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "AcknowledgeOutSwapHtlc", func() proto.Message {
		return &AcknowledgeOutSwapHtlcRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*AcknowledgeOutSwapHtlcRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.AcknowledgeOutSwapHtlc(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "SignInSwapForfeit", func() proto.Message {
		return &SignInSwapForfeitRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*SignInSwapForfeitRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SignInSwapForfeit(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "SubmitOutSwapForfeitSignature", func() proto.Message {
		return &SubmitOutSwapForfeitSignatureRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*SubmitOutSwapForfeitSignatureRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SubmitOutSwapForfeitSignature(ctx, req)
	})
}

// RequestChannelId calls the RequestChannelId RPC.
func (c *SwapServiceMailboxClient) RequestChannelId(ctx context.Context, req *RequestChannelIdRequest, opts ...rpc.RPCOptions) (*RequestChannelIdResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "RequestChannelId",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(RequestChannelIdResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// CreateInSwap calls the CreateInSwap RPC.
func (c *SwapServiceMailboxClient) CreateInSwap(ctx context.Context, req *CreateInSwapRequest, opts ...rpc.RPCOptions) (*CreateInSwapResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "CreateInSwap",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(CreateInSwapResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// QuoteInSwap calls the QuoteInSwap RPC.
func (c *SwapServiceMailboxClient) QuoteInSwap(ctx context.Context, req *QuoteInSwapRequest, opts ...rpc.RPCOptions) (*QuoteInSwapResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "QuoteInSwap",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(QuoteInSwapResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// CreateCredit calls the CreateCredit RPC.
func (c *SwapServiceMailboxClient) CreateCredit(ctx context.Context, req *CreateCreditRequest, opts ...rpc.RPCOptions) (*CreateCreditResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "CreateCredit",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(CreateCreditResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// RedeemCredit calls the RedeemCredit RPC.
func (c *SwapServiceMailboxClient) RedeemCredit(ctx context.Context, req *RedeemCreditRequest, opts ...rpc.RPCOptions) (*RedeemCreditResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "RedeemCredit",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(RedeemCreditResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ListCredits calls the ListCredits RPC.
func (c *SwapServiceMailboxClient) ListCredits(ctx context.Context, req *ListCreditsRequest, opts ...rpc.RPCOptions) (*ListCreditsResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "ListCredits",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(ListCreditsResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// AuthorizeInSwapRefund calls the AuthorizeInSwapRefund RPC.
func (c *SwapServiceMailboxClient) AuthorizeInSwapRefund(ctx context.Context, req *AuthorizeInSwapRefundRequest, opts ...rpc.RPCOptions) (*AuthorizeInSwapRefundResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "AuthorizeInSwapRefund",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(AuthorizeInSwapRefundResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// AcknowledgeOutSwapHtlc calls the AcknowledgeOutSwapHtlc RPC.
func (c *SwapServiceMailboxClient) AcknowledgeOutSwapHtlc(ctx context.Context, req *AcknowledgeOutSwapHtlcRequest, opts ...rpc.RPCOptions) (*AcknowledgeOutSwapHtlcResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "AcknowledgeOutSwapHtlc",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(AcknowledgeOutSwapHtlcResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SignInSwapForfeit calls the SignInSwapForfeit RPC.
func (c *SwapServiceMailboxClient) SignInSwapForfeit(ctx context.Context, req *SignInSwapForfeitRequest, opts ...rpc.RPCOptions) (*SignInSwapForfeitResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "SignInSwapForfeit",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(SignInSwapForfeitResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SubmitOutSwapForfeitSignature calls the SubmitOutSwapForfeitSignature RPC.
func (c *SwapServiceMailboxClient) SubmitOutSwapForfeitSignature(ctx context.Context, req *SubmitOutSwapForfeitSignatureRequest, opts ...rpc.RPCOptions) (*SubmitOutSwapForfeitSignatureResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "SubmitOutSwapForfeitSignature",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(SubmitOutSwapForfeitSignatureResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
