// Code generated by protoc-gen-mailboxrpc. DO NOT EDIT.

package swaprpc

import (
	context "context"
	fmt "fmt"
	rpc "github.com/lightninglabs/darepo-client/mailbox/rpc"
	proto "google.golang.org/protobuf/proto"
)

// SwapServiceMailboxClient is a typed mailbox RPC client for SwapService.
type SwapServiceMailboxClient struct {
	// C is the underlying RPC-over-mailbox runtime client.
	C rpc.RPCClient
}

// NewSwapServiceMailboxClient creates a typed mailbox client.
func NewSwapServiceMailboxClient(c rpc.RPCClient) *SwapServiceMailboxClient {
	return &SwapServiceMailboxClient{
		C: c,
	}
}

// SwapServiceMailboxServer is the mailbox server interface for SwapService.
type SwapServiceMailboxServer interface {
	// RequestChannelId handles RequestChannelId.
	RequestChannelId(ctx context.Context, req *RequestChannelIdRequest) (*RequestChannelIdResponse, error)
	// CreateInSwap handles CreateInSwap.
	CreateInSwap(ctx context.Context, req *CreateInSwapRequest) (*CreateInSwapResponse, error)
	// AuthorizeInSwapRefund handles AuthorizeInSwapRefund.
	AuthorizeInSwapRefund(ctx context.Context, req *AuthorizeInSwapRefundRequest) (*AuthorizeInSwapRefundResponse, error)
	// AcknowledgeOutSwapHtlc handles AcknowledgeOutSwapHtlc.
	AcknowledgeOutSwapHtlc(ctx context.Context, req *AcknowledgeOutSwapHtlcRequest) (*AcknowledgeOutSwapHtlcResponse, error)
}

// RegisterSwapServiceMailboxServer registers handlers for SwapService.
func RegisterSwapServiceMailboxServer(r rpc.Router, impl SwapServiceMailboxServer) {
	r.Handle("swaprpc.SwapService", "RequestChannelId", func() proto.Message {
		return &RequestChannelIdRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*RequestChannelIdRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.RequestChannelId(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "CreateInSwap", func() proto.Message {
		return &CreateInSwapRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*CreateInSwapRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.CreateInSwap(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "AuthorizeInSwapRefund", func() proto.Message {
		return &AuthorizeInSwapRefundRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*AuthorizeInSwapRefundRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.AuthorizeInSwapRefund(ctx, req)
	})
	r.Handle("swaprpc.SwapService", "AcknowledgeOutSwapHtlc", func() proto.Message {
		return &AcknowledgeOutSwapHtlcRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*AcknowledgeOutSwapHtlcRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.AcknowledgeOutSwapHtlc(ctx, req)
	})
}

// RequestChannelId calls the RequestChannelId RPC.
func (c *SwapServiceMailboxClient) RequestChannelId(ctx context.Context, req *RequestChannelIdRequest, opts ...rpc.RPCOptions) (*RequestChannelIdResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "RequestChannelId",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(RequestChannelIdResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// CreateInSwap calls the CreateInSwap RPC.
func (c *SwapServiceMailboxClient) CreateInSwap(ctx context.Context, req *CreateInSwapRequest, opts ...rpc.RPCOptions) (*CreateInSwapResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "CreateInSwap",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(CreateInSwapResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// AuthorizeInSwapRefund calls the AuthorizeInSwapRefund RPC.
func (c *SwapServiceMailboxClient) AuthorizeInSwapRefund(ctx context.Context, req *AuthorizeInSwapRefundRequest, opts ...rpc.RPCOptions) (*AuthorizeInSwapRefundResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "AuthorizeInSwapRefund",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(AuthorizeInSwapRefundResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// AcknowledgeOutSwapHtlc calls the AcknowledgeOutSwapHtlc RPC.
func (c *SwapServiceMailboxClient) AcknowledgeOutSwapHtlc(ctx context.Context, req *AcknowledgeOutSwapHtlcRequest, opts ...rpc.RPCOptions) (*AcknowledgeOutSwapHtlcResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "swaprpc.SwapService",
		Method:  "AcknowledgeOutSwapHtlc",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(AcknowledgeOutSwapHtlcResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
