// Code generated by protoc-gen-mailboxrpc. DO NOT EDIT.

package daemonrpc

import (
	context "context"
	fmt "fmt"
	rpc "github.com/lightninglabs/darepo-client/mailbox/rpc"
	proto "google.golang.org/protobuf/proto"
)

// DaemonServiceMailboxClient is a typed mailbox RPC client for DaemonService.
type DaemonServiceMailboxClient struct {
	// C is the underlying RPC-over-mailbox runtime client.
	C rpc.RPCClient
}

// NewDaemonServiceMailboxClient creates a typed mailbox client.
func NewDaemonServiceMailboxClient(c rpc.RPCClient) *DaemonServiceMailboxClient {
	return &DaemonServiceMailboxClient{
		C: c,
	}
}

// DaemonServiceMailboxServer is the mailbox server interface for DaemonService.
type DaemonServiceMailboxServer interface {
	// GetInfo handles GetInfo.
	GetInfo(ctx context.Context, req *GetInfoRequest) (*GetInfoResponse, error)
}

// RegisterDaemonServiceMailboxServer registers handlers for DaemonService.
func RegisterDaemonServiceMailboxServer(r rpc.Router, impl DaemonServiceMailboxServer) {
	r.Handle("daemonrpc.DaemonService", "GetInfo", func() proto.Message {
		return &GetInfoRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*GetInfoRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.GetInfo(ctx, req)
	})
}

// GetInfo calls the GetInfo RPC.
func (c *DaemonServiceMailboxClient) GetInfo(ctx context.Context, req *GetInfoRequest, opts ...rpc.RPCOptions) (*GetInfoResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "daemonrpc.DaemonService",
		Method:  "GetInfo",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(GetInfoResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
