// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type ChainInfo struct {
	ID          int64
	ChainName   string
	GenesisHash []byte
}

type IndexerReceiveScript struct {
	PrincipalMailboxID string
	PkScript           []byte
	ExpiresAtUnixS     int64
	Label              string
	UpdatedAt          int64
	OwnerPubkey        []byte
	OperatorPubkey     []byte
	ExitDelay          sql.NullInt64
}

type IndexerVtxoEvent struct {
	EventID       int64
	PkScript      []byte
	EventType     string
	OutpointHash  []byte
	OutpointIndex int32
	Status        string
	CreatedAt     int64
}

type MailboxAckCursor struct {
	Recipient string
	AckCursor int64
}

type MailboxEnvelope struct {
	EventSeq  int64
	Recipient string
	MsgID     string
	Envelope  []byte
	CreatedAt int64
}

type OorCheckpoint struct {
	SessionDbID     int32
	CheckpointIndex int32
	InputTxid       []byte
	InputVout       int32
	CheckpointPsbt  []byte
}

type OorRecipientEvent struct {
	RecipientPkScript []byte
	EventID           int64
	SessionDbID       int32
	OutputIndex       int32
	Value             int64
	CreatedAt         int64
}

type OorSession struct {
	ID          int64
	SessionID   []byte
	State       string
	ArkPsbt     []byte
	CreatedAt   int64
	UpdatedAt   int64
	ExpiresAt   int64
	FinalizedAt sql.NullInt64
}

type Round struct {
	RoundID               []byte
	FinalTx               []byte
	CommitmentTxid        string
	ConfirmationHeight    sql.NullInt32
	ConfirmationBlockHash []byte
	Status                string
	SweepKey              []byte
	CsvDelay              int32
	CreatedAt             int64
	UpdatedAt             int64
}

type RoundClientRegistration struct {
	RoundID          []byte
	ClientID         []byte
	RegistrationData []byte
}

type RoundConnectorDescriptor struct {
	RoundID       []byte
	OutputIndex   int32
	NumLeaves     int32
	ForfeitScript []byte
}

type RoundForfeitInfo struct {
	RoundID              []byte
	OutpointHash         []byte
	OutpointIndex        int32
	ForfeitTx            []byte
	ConnectorOutputIndex int32
	LeafIndex            int32
}

type RoundStatus struct {
	Status string
}

type RoundVtxoTree struct {
	RoundID          []byte
	BatchOutputIndex int32
}

type Vtxo struct {
	OutpointHash      []byte
	OutpointIndex     int32
	RoundID           []byte
	BatchOutputIndex  sql.NullInt32
	Amount            int64
	ExitDelay         int32
	PkScript          []byte
	OwnerKey          []byte
	OperatorKey       []byte
	OperatorKeyFamily int32
	OperatorKeyIndex  int32
	Status            string
	LockOwnerKind     sql.NullString
	LockOwnerID       []byte
}

type VtxoStatus struct {
	Status string
}

type VtxoTreeCosigner struct {
	RoundID          []byte
	BatchOutputIndex int32
	NodeID           string
	CosignerKey      []byte
	KeyIndex         int32
}

type VtxoTreeNode struct {
	RoundID           []byte
	BatchOutputIndex  int32
	NodeID            string
	ParentNodeID      sql.NullString
	ParentOutputIndex sql.NullInt32
	Depth             int32
	IsLeaf            int32
	InputHash         []byte
	InputIndex        int32
	Amount            int64
	Signature         []byte
	FinalKey          []byte
}

type VtxoTreeNodeOutput struct {
	RoundID          []byte
	BatchOutputIndex int32
	NodeID           string
	OutputIndex      int32
	Value            int64
	PkScript         []byte
}
