// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: round.sql

package sqlc

import (
	"context"
	"database/sql"
)

const CountUnspentVTXOs = `-- name: CountUnspentVTXOs :one
SELECT COUNT(*) FROM vtxos WHERE spent = FALSE
`

func (q *Queries) CountUnspentVTXOs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUnspentVTXOs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteClientTreeTxids = `-- name: DeleteClientTreeTxids :exec
DELETE FROM client_tree_txids WHERE round_id = $1 AND client_key = $2
`

type DeleteClientTreeTxidsParams struct {
	RoundID   string
	ClientKey []byte
}

func (q *Queries) DeleteClientTreeTxids(ctx context.Context, arg DeleteClientTreeTxidsParams) error {
	_, err := q.db.ExecContext(ctx, DeleteClientTreeTxids, arg.RoundID, arg.ClientKey)
	return err
}

const FinalizeRound = `-- name: FinalizeRound :exec
UPDATE rounds
SET status = 'confirmed',
    commitment_txid = $2,
    confirmation_height = $3,
    confirmation_block_hash = $4,
    last_update_time = $5
WHERE round_id = $1
`

type FinalizeRoundParams struct {
	RoundID               string
	CommitmentTxid        []byte
	ConfirmationHeight    sql.NullInt32
	ConfirmationBlockHash []byte
	LastUpdateTime        int64
}

func (q *Queries) FinalizeRound(ctx context.Context, arg FinalizeRoundParams) error {
	_, err := q.db.ExecContext(ctx, FinalizeRound,
		arg.RoundID,
		arg.CommitmentTxid,
		arg.ConfirmationHeight,
		arg.ConfirmationBlockHash,
		arg.LastUpdateTime,
	)
	return err
}

const GetClientTreeByTxid = `-- name: GetClientTreeByTxid :one
SELECT t.round_id, t.client_key, t.tree_data FROM round_client_trees t
JOIN client_tree_txids idx ON t.round_id = idx.round_id AND t.client_key = idx.client_key
WHERE idx.txid = $1
`

func (q *Queries) GetClientTreeByTxid(ctx context.Context, txid []byte) (RoundClientTree, error) {
	row := q.db.QueryRowContext(ctx, GetClientTreeByTxid, txid)
	var i RoundClientTree
	err := row.Scan(&i.RoundID, &i.ClientKey, &i.TreeData)
	return i, err
}

const GetClientTreeTxidInfo = `-- name: GetClientTreeTxidInfo :one
SELECT txid, round_id, client_key, tree_level, output_index FROM client_tree_txids WHERE txid = $1
`

func (q *Queries) GetClientTreeTxidInfo(ctx context.Context, txid []byte) (ClientTreeTxid, error) {
	row := q.db.QueryRowContext(ctx, GetClientTreeTxidInfo, txid)
	var i ClientTreeTxid
	err := row.Scan(
		&i.Txid,
		&i.RoundID,
		&i.ClientKey,
		&i.TreeLevel,
		&i.OutputIndex,
	)
	return i, err
}

const GetClientTreeTxids = `-- name: GetClientTreeTxids :many
SELECT txid, tree_level, output_index FROM client_tree_txids
WHERE round_id = $1 AND client_key = $2
ORDER BY tree_level ASC
`

type GetClientTreeTxidsParams struct {
	RoundID   string
	ClientKey []byte
}

type GetClientTreeTxidsRow struct {
	Txid        []byte
	TreeLevel   int32
	OutputIndex int32
}

func (q *Queries) GetClientTreeTxids(ctx context.Context, arg GetClientTreeTxidsParams) ([]GetClientTreeTxidsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetClientTreeTxids, arg.RoundID, arg.ClientKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClientTreeTxidsRow
	for rows.Next() {
		var i GetClientTreeTxidsRow
		if err := rows.Scan(&i.Txid, &i.TreeLevel, &i.OutputIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRound = `-- name: GetRound :one
SELECT round_id, start_height, confirmation_height, confirmation_block_hash, commitment_tx, commitment_txid, vtxt_tree, status, creation_time, last_update_time FROM rounds WHERE round_id = $1
`

func (q *Queries) GetRound(ctx context.Context, roundID string) (Round, error) {
	row := q.db.QueryRowContext(ctx, GetRound, roundID)
	var i Round
	err := row.Scan(
		&i.RoundID,
		&i.StartHeight,
		&i.ConfirmationHeight,
		&i.ConfirmationBlockHash,
		&i.CommitmentTx,
		&i.CommitmentTxid,
		&i.VtxtTree,
		&i.Status,
		&i.CreationTime,
		&i.LastUpdateTime,
	)
	return i, err
}

const GetRoundBoardingIntents = `-- name: GetRoundBoardingIntents :many
SELECT round_id, outpoint_hash, outpoint_index, client_key, operator_key, exit_delay, tx_proof, input_index, input_signature FROM round_boarding_intents WHERE round_id = $1
`

func (q *Queries) GetRoundBoardingIntents(ctx context.Context, roundID string) ([]RoundBoardingIntent, error) {
	rows, err := q.db.QueryContext(ctx, GetRoundBoardingIntents, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoundBoardingIntent
	for rows.Next() {
		var i RoundBoardingIntent
		if err := rows.Scan(
			&i.RoundID,
			&i.OutpointHash,
			&i.OutpointIndex,
			&i.ClientKey,
			&i.OperatorKey,
			&i.ExitDelay,
			&i.TxProof,
			&i.InputIndex,
			&i.InputSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRoundByCommitmentTxid = `-- name: GetRoundByCommitmentTxid :one
SELECT round_id, start_height, confirmation_height, confirmation_block_hash, commitment_tx, commitment_txid, vtxt_tree, status, creation_time, last_update_time FROM rounds WHERE commitment_txid = $1
`

func (q *Queries) GetRoundByCommitmentTxid(ctx context.Context, commitmentTxid []byte) (Round, error) {
	row := q.db.QueryRowContext(ctx, GetRoundByCommitmentTxid, commitmentTxid)
	var i Round
	err := row.Scan(
		&i.RoundID,
		&i.StartHeight,
		&i.ConfirmationHeight,
		&i.ConfirmationBlockHash,
		&i.CommitmentTx,
		&i.CommitmentTxid,
		&i.VtxtTree,
		&i.Status,
		&i.CreationTime,
		&i.LastUpdateTime,
	)
	return i, err
}

const GetRoundClientTree = `-- name: GetRoundClientTree :one
SELECT round_id, client_key, tree_data FROM round_client_trees
WHERE round_id = $1 AND client_key = $2
`

type GetRoundClientTreeParams struct {
	RoundID   string
	ClientKey []byte
}

func (q *Queries) GetRoundClientTree(ctx context.Context, arg GetRoundClientTreeParams) (RoundClientTree, error) {
	row := q.db.QueryRowContext(ctx, GetRoundClientTree, arg.RoundID, arg.ClientKey)
	var i RoundClientTree
	err := row.Scan(&i.RoundID, &i.ClientKey, &i.TreeData)
	return i, err
}

const GetRoundClientTrees = `-- name: GetRoundClientTrees :many
SELECT round_id, client_key, tree_data FROM round_client_trees WHERE round_id = $1
`

func (q *Queries) GetRoundClientTrees(ctx context.Context, roundID string) ([]RoundClientTree, error) {
	rows, err := q.db.QueryContext(ctx, GetRoundClientTrees, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoundClientTree
	for rows.Next() {
		var i RoundClientTree
		if err := rows.Scan(&i.RoundID, &i.ClientKey, &i.TreeData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRoundVtxoRequests = `-- name: GetRoundVtxoRequests :many
SELECT round_id, request_index, amount, pk_script, expiry, client_pubkey, operator_pubkey, signing_key_family, signing_key_index, signing_pubkey FROM round_vtxo_requests
WHERE round_id = $1
ORDER BY request_index ASC
`

func (q *Queries) GetRoundVtxoRequests(ctx context.Context, roundID string) ([]RoundVtxoRequest, error) {
	rows, err := q.db.QueryContext(ctx, GetRoundVtxoRequests, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoundVtxoRequest
	for rows.Next() {
		var i RoundVtxoRequest
		if err := rows.Scan(
			&i.RoundID,
			&i.RequestIndex,
			&i.Amount,
			&i.PkScript,
			&i.Expiry,
			&i.ClientPubkey,
			&i.OperatorPubkey,
			&i.SigningKeyFamily,
			&i.SigningKeyIndex,
			&i.SigningPubkey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetVTXO = `-- name: GetVTXO :one
SELECT outpoint_hash, outpoint_index, round_id, amount, pk_script, expiry, client_key_family, client_key_index, client_pubkey, operator_pubkey, tree_path, spent, creation_time, last_update_time FROM vtxos
WHERE outpoint_hash = $1 AND outpoint_index = $2
`

type GetVTXOParams struct {
	OutpointHash  []byte
	OutpointIndex int32
}

func (q *Queries) GetVTXO(ctx context.Context, arg GetVTXOParams) (Vtxo, error) {
	row := q.db.QueryRowContext(ctx, GetVTXO, arg.OutpointHash, arg.OutpointIndex)
	var i Vtxo
	err := row.Scan(
		&i.OutpointHash,
		&i.OutpointIndex,
		&i.RoundID,
		&i.Amount,
		&i.PkScript,
		&i.Expiry,
		&i.ClientKeyFamily,
		&i.ClientKeyIndex,
		&i.ClientPubkey,
		&i.OperatorPubkey,
		&i.TreePath,
		&i.Spent,
		&i.CreationTime,
		&i.LastUpdateTime,
	)
	return i, err
}

const InsertClientTreeTxid = `-- name: InsertClientTreeTxid :exec

INSERT INTO client_tree_txids (txid, round_id, client_key, tree_level, output_index)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (txid, round_id, client_key) DO NOTHING
`

type InsertClientTreeTxidParams struct {
	Txid        []byte
	RoundID     string
	ClientKey   []byte
	TreeLevel   int32
	OutputIndex int32
}

// Client tree txids queries.
func (q *Queries) InsertClientTreeTxid(ctx context.Context, arg InsertClientTreeTxidParams) error {
	_, err := q.db.ExecContext(ctx, InsertClientTreeTxid,
		arg.Txid,
		arg.RoundID,
		arg.ClientKey,
		arg.TreeLevel,
		arg.OutputIndex,
	)
	return err
}

const InsertRound = `-- name: InsertRound :exec

INSERT INTO rounds (
    round_id, confirmation_height, confirmation_block_hash, commitment_tx,
    commitment_txid, vtxt_tree, status, creation_time, last_update_time,
    start_height
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (round_id) DO UPDATE SET
    confirmation_height = COALESCE(excluded.confirmation_height, rounds.confirmation_height),
    confirmation_block_hash = COALESCE(excluded.confirmation_block_hash, rounds.confirmation_block_hash),
    commitment_tx = COALESCE(excluded.commitment_tx, rounds.commitment_tx),
    commitment_txid = COALESCE(excluded.commitment_txid, rounds.commitment_txid),
    vtxt_tree = COALESCE(excluded.vtxt_tree, rounds.vtxt_tree),
    status = excluded.status,
    last_update_time = excluded.last_update_time
`

type InsertRoundParams struct {
	RoundID               string
	ConfirmationHeight    sql.NullInt32
	ConfirmationBlockHash []byte
	CommitmentTx          []byte
	CommitmentTxid        []byte
	VtxtTree              []byte
	Status                string
	CreationTime          int64
	LastUpdateTime        int64
	StartHeight           int32
}

// Round queries.
func (q *Queries) InsertRound(ctx context.Context, arg InsertRoundParams) error {
	_, err := q.db.ExecContext(ctx, InsertRound,
		arg.RoundID,
		arg.ConfirmationHeight,
		arg.ConfirmationBlockHash,
		arg.CommitmentTx,
		arg.CommitmentTxid,
		arg.VtxtTree,
		arg.Status,
		arg.CreationTime,
		arg.LastUpdateTime,
		arg.StartHeight,
	)
	return err
}

const InsertRoundBoardingIntent = `-- name: InsertRoundBoardingIntent :exec

INSERT INTO round_boarding_intents (
    round_id, outpoint_hash, outpoint_index, client_key, operator_key,
    exit_delay, tx_proof, input_index, input_signature
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (round_id, outpoint_hash, outpoint_index) DO UPDATE SET
    input_index = COALESCE(excluded.input_index, round_boarding_intents.input_index),
    input_signature = COALESCE(excluded.input_signature, round_boarding_intents.input_signature)
`

type InsertRoundBoardingIntentParams struct {
	RoundID        string
	OutpointHash   []byte
	OutpointIndex  int32
	ClientKey      []byte
	OperatorKey    []byte
	ExitDelay      int32
	TxProof        []byte
	InputIndex     sql.NullInt32
	InputSignature []byte
}

// Round boarding intents queries.
func (q *Queries) InsertRoundBoardingIntent(ctx context.Context, arg InsertRoundBoardingIntentParams) error {
	_, err := q.db.ExecContext(ctx, InsertRoundBoardingIntent,
		arg.RoundID,
		arg.OutpointHash,
		arg.OutpointIndex,
		arg.ClientKey,
		arg.OperatorKey,
		arg.ExitDelay,
		arg.TxProof,
		arg.InputIndex,
		arg.InputSignature,
	)
	return err
}

const InsertRoundClientTree = `-- name: InsertRoundClientTree :exec

INSERT INTO round_client_trees (round_id, client_key, tree_data)
VALUES ($1, $2, $3)
ON CONFLICT (round_id, client_key) DO UPDATE
SET tree_data = excluded.tree_data
`

type InsertRoundClientTreeParams struct {
	RoundID   string
	ClientKey []byte
	TreeData  []byte
}

// Client trees queries.
func (q *Queries) InsertRoundClientTree(ctx context.Context, arg InsertRoundClientTreeParams) error {
	_, err := q.db.ExecContext(ctx, InsertRoundClientTree, arg.RoundID, arg.ClientKey, arg.TreeData)
	return err
}

const InsertRoundVtxoRequest = `-- name: InsertRoundVtxoRequest :exec

INSERT INTO round_vtxo_requests (
    round_id, request_index, amount, pk_script, expiry, client_pubkey,
    operator_pubkey, signing_key_family, signing_key_index, signing_pubkey
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
    ON CONFLICT (round_id, request_index) DO NOTHING
`

type InsertRoundVtxoRequestParams struct {
	RoundID          string
	RequestIndex     int32
	Amount           int64
	PkScript         []byte
	Expiry           int32
	ClientPubkey     []byte
	OperatorPubkey   []byte
	SigningKeyFamily int32
	SigningKeyIndex  int32
	SigningPubkey    []byte
}

// Round VTXO request queries.
func (q *Queries) InsertRoundVtxoRequest(ctx context.Context, arg InsertRoundVtxoRequestParams) error {
	_, err := q.db.ExecContext(ctx, InsertRoundVtxoRequest,
		arg.RoundID,
		arg.RequestIndex,
		arg.Amount,
		arg.PkScript,
		arg.Expiry,
		arg.ClientPubkey,
		arg.OperatorPubkey,
		arg.SigningKeyFamily,
		arg.SigningKeyIndex,
		arg.SigningPubkey,
	)
	return err
}

const InsertVTXO = `-- name: InsertVTXO :exec

INSERT INTO vtxos (
    outpoint_hash, outpoint_index, round_id, amount, pk_script, expiry,
    client_key_family, client_key_index, client_pubkey, operator_pubkey,
    tree_path, spent, creation_time, last_update_time
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (outpoint_hash, outpoint_index) DO NOTHING
`

type InsertVTXOParams struct {
	OutpointHash    []byte
	OutpointIndex   int32
	RoundID         string
	Amount          int64
	PkScript        []byte
	Expiry          int32
	ClientKeyFamily int32
	ClientKeyIndex  int32
	ClientPubkey    []byte
	OperatorPubkey  []byte
	TreePath        []byte
	Spent           bool
	CreationTime    int64
	LastUpdateTime  int64
}

// VTXO queries.
func (q *Queries) InsertVTXO(ctx context.Context, arg InsertVTXOParams) error {
	_, err := q.db.ExecContext(ctx, InsertVTXO,
		arg.OutpointHash,
		arg.OutpointIndex,
		arg.RoundID,
		arg.Amount,
		arg.PkScript,
		arg.Expiry,
		arg.ClientKeyFamily,
		arg.ClientKeyIndex,
		arg.ClientPubkey,
		arg.OperatorPubkey,
		arg.TreePath,
		arg.Spent,
		arg.CreationTime,
		arg.LastUpdateTime,
	)
	return err
}

const ListActiveRounds = `-- name: ListActiveRounds :many
SELECT round_id, start_height, confirmation_height, confirmation_block_hash, commitment_tx, commitment_txid, vtxt_tree, status, creation_time, last_update_time FROM rounds WHERE status = 'input_sig_sent' ORDER BY creation_time ASC
`

func (q *Queries) ListActiveRounds(ctx context.Context) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, ListActiveRounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.RoundID,
			&i.StartHeight,
			&i.ConfirmationHeight,
			&i.ConfirmationBlockHash,
			&i.CommitmentTx,
			&i.CommitmentTxid,
			&i.VtxtTree,
			&i.Status,
			&i.CreationTime,
			&i.LastUpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAllVTXOs = `-- name: ListAllVTXOs :many
SELECT outpoint_hash, outpoint_index, round_id, amount, pk_script, expiry, client_key_family, client_key_index, client_pubkey, operator_pubkey, tree_path, spent, creation_time, last_update_time FROM vtxos ORDER BY creation_time DESC
`

func (q *Queries) ListAllVTXOs(ctx context.Context) ([]Vtxo, error) {
	rows, err := q.db.QueryContext(ctx, ListAllVTXOs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vtxo
	for rows.Next() {
		var i Vtxo
		if err := rows.Scan(
			&i.OutpointHash,
			&i.OutpointIndex,
			&i.RoundID,
			&i.Amount,
			&i.PkScript,
			&i.Expiry,
			&i.ClientKeyFamily,
			&i.ClientKeyIndex,
			&i.ClientPubkey,
			&i.OperatorPubkey,
			&i.TreePath,
			&i.Spent,
			&i.CreationTime,
			&i.LastUpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRoundsByStatus = `-- name: ListRoundsByStatus :many
SELECT round_id, start_height, confirmation_height, confirmation_block_hash, commitment_tx, commitment_txid, vtxt_tree, status, creation_time, last_update_time FROM rounds WHERE status = $1 ORDER BY creation_time DESC
`

func (q *Queries) ListRoundsByStatus(ctx context.Context, status string) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, ListRoundsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.RoundID,
			&i.StartHeight,
			&i.ConfirmationHeight,
			&i.ConfirmationBlockHash,
			&i.CommitmentTx,
			&i.CommitmentTxid,
			&i.VtxtTree,
			&i.Status,
			&i.CreationTime,
			&i.LastUpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnspentVTXOs = `-- name: ListUnspentVTXOs :many
SELECT outpoint_hash, outpoint_index, round_id, amount, pk_script, expiry, client_key_family, client_key_index, client_pubkey, operator_pubkey, tree_path, spent, creation_time, last_update_time FROM vtxos WHERE spent = FALSE ORDER BY creation_time DESC
`

func (q *Queries) ListUnspentVTXOs(ctx context.Context) ([]Vtxo, error) {
	rows, err := q.db.QueryContext(ctx, ListUnspentVTXOs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vtxo
	for rows.Next() {
		var i Vtxo
		if err := rows.Scan(
			&i.OutpointHash,
			&i.OutpointIndex,
			&i.RoundID,
			&i.Amount,
			&i.PkScript,
			&i.Expiry,
			&i.ClientKeyFamily,
			&i.ClientKeyIndex,
			&i.ClientPubkey,
			&i.OperatorPubkey,
			&i.TreePath,
			&i.Spent,
			&i.CreationTime,
			&i.LastUpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListVTXOsByRound = `-- name: ListVTXOsByRound :many
SELECT outpoint_hash, outpoint_index, round_id, amount, pk_script, expiry, client_key_family, client_key_index, client_pubkey, operator_pubkey, tree_path, spent, creation_time, last_update_time FROM vtxos WHERE round_id = $1 ORDER BY creation_time DESC
`

func (q *Queries) ListVTXOsByRound(ctx context.Context, roundID string) ([]Vtxo, error) {
	rows, err := q.db.QueryContext(ctx, ListVTXOsByRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vtxo
	for rows.Next() {
		var i Vtxo
		if err := rows.Scan(
			&i.OutpointHash,
			&i.OutpointIndex,
			&i.RoundID,
			&i.Amount,
			&i.PkScript,
			&i.Expiry,
			&i.ClientKeyFamily,
			&i.ClientKeyIndex,
			&i.ClientPubkey,
			&i.OperatorPubkey,
			&i.TreePath,
			&i.Spent,
			&i.CreationTime,
			&i.LastUpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkVTXOSpent = `-- name: MarkVTXOSpent :exec
UPDATE vtxos SET spent = TRUE, last_update_time = $3
WHERE outpoint_hash = $1 AND outpoint_index = $2
`

type MarkVTXOSpentParams struct {
	OutpointHash   []byte
	OutpointIndex  int32
	LastUpdateTime int64
}

func (q *Queries) MarkVTXOSpent(ctx context.Context, arg MarkVTXOSpentParams) error {
	_, err := q.db.ExecContext(ctx, MarkVTXOSpent, arg.OutpointHash, arg.OutpointIndex, arg.LastUpdateTime)
	return err
}

const SumUnspentVTXOAmounts = `-- name: SumUnspentVTXOAmounts :one
SELECT COALESCE(SUM(amount), 0) as total FROM vtxos WHERE spent = FALSE
`

func (q *Queries) SumUnspentVTXOAmounts(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, SumUnspentVTXOAmounts)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const UpdateRoundBoardingIntentSignature = `-- name: UpdateRoundBoardingIntentSignature :exec
UPDATE round_boarding_intents
SET input_signature = $4, input_index = $5
WHERE round_id = $1 AND outpoint_hash = $2 AND outpoint_index = $3
`

type UpdateRoundBoardingIntentSignatureParams struct {
	RoundID        string
	OutpointHash   []byte
	OutpointIndex  int32
	InputSignature []byte
	InputIndex     sql.NullInt32
}

func (q *Queries) UpdateRoundBoardingIntentSignature(ctx context.Context, arg UpdateRoundBoardingIntentSignatureParams) error {
	_, err := q.db.ExecContext(ctx, UpdateRoundBoardingIntentSignature,
		arg.RoundID,
		arg.OutpointHash,
		arg.OutpointIndex,
		arg.InputSignature,
		arg.InputIndex,
	)
	return err
}

const UpdateRoundStatus = `-- name: UpdateRoundStatus :exec
UPDATE rounds
SET status = $2, last_update_time = $3
WHERE round_id = $1
`

type UpdateRoundStatusParams struct {
	RoundID        string
	Status         string
	LastUpdateTime int64
}

func (q *Queries) UpdateRoundStatus(ctx context.Context, arg UpdateRoundStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateRoundStatus, arg.RoundID, arg.Status, arg.LastUpdateTime)
	return err
}
