// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transport.sql

package sqlc

import (
	"context"
	"database/sql"
)

const ClaimMailboxEgress = `-- name: ClaimMailboxEgress :one
UPDATE mailbox_egress
SET status = 'claimed',
    claim_owner = $2,
    claim_token = $3,
    claim_until = $4,
    attempts = attempts + 1,
    updated_at = $5
WHERE id = $1
  AND next_attempt_at <= $5
  AND attempts < max_attempts
  AND (
    status = 'pending' OR
    (status = 'claimed' AND claim_until <= $5)
  )
RETURNING id, connector, local_mailbox_id, remote_mailbox_id,
    rpc_kind, service, method, correlation_id, reply_to, msg_id,
    idempotency_key, envelope, status, attempts, max_attempts,
    next_attempt_at, claim_owner, claim_token, claim_until,
    last_error, created_at, updated_at, sent_at
`

type ClaimMailboxEgressParams struct {
	ID         string
	ClaimOwner sql.NullString
	ClaimToken sql.NullString
	ClaimUntil sql.NullInt64
	UpdatedAt  int64
}

func (q *Queries) ClaimMailboxEgress(ctx context.Context, arg ClaimMailboxEgressParams) (MailboxEgress, error) {
	row := q.db.QueryRowContext(ctx, ClaimMailboxEgress,
		arg.ID,
		arg.ClaimOwner,
		arg.ClaimToken,
		arg.ClaimUntil,
		arg.UpdatedAt,
	)
	var i MailboxEgress
	err := row.Scan(
		&i.ID,
		&i.Connector,
		&i.LocalMailboxID,
		&i.RemoteMailboxID,
		&i.RpcKind,
		&i.Service,
		&i.Method,
		&i.CorrelationID,
		&i.ReplyTo,
		&i.MsgID,
		&i.IdempotencyKey,
		&i.Envelope,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.ClaimOwner,
		&i.ClaimToken,
		&i.ClaimUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const GetMailboxIngressCursor = `-- name: GetMailboxIngressCursor :one
SELECT local_mailbox_id, remote_mailbox_id, pull_cursor,
    dispatch_committed_to, ack_target, ack_committed_to, last_pull_at,
    last_dispatch_at, last_ack_at, last_error, created_at, updated_at
FROM mailbox_ingress_cursors
WHERE local_mailbox_id = $1
`

func (q *Queries) GetMailboxIngressCursor(ctx context.Context, localMailboxID string) (MailboxIngressCursor, error) {
	row := q.db.QueryRowContext(ctx, GetMailboxIngressCursor, localMailboxID)
	var i MailboxIngressCursor
	err := row.Scan(
		&i.LocalMailboxID,
		&i.RemoteMailboxID,
		&i.PullCursor,
		&i.DispatchCommittedTo,
		&i.AckTarget,
		&i.AckCommittedTo,
		&i.LastPullAt,
		&i.LastDispatchAt,
		&i.LastAckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertMailboxEgress = `-- name: InsertMailboxEgress :exec
INSERT INTO mailbox_egress (
    id, connector, local_mailbox_id, remote_mailbox_id,
    rpc_kind, service, method, correlation_id, reply_to,
    msg_id, idempotency_key, envelope, status, attempts,
    max_attempts, next_attempt_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, 'pending', 0,
    $13, $14, $15, $15
)
ON CONFLICT (connector, local_mailbox_id, idempotency_key) DO UPDATE SET
    remote_mailbox_id = excluded.remote_mailbox_id,
    rpc_kind = excluded.rpc_kind,
    service = excluded.service,
    method = excluded.method,
    correlation_id = excluded.correlation_id,
    reply_to = excluded.reply_to,
    msg_id = excluded.msg_id,
    envelope = excluded.envelope,
    status = 'pending',
    attempts = 0,
    max_attempts = excluded.max_attempts,
    next_attempt_at = excluded.next_attempt_at,
    claim_owner = NULL,
    claim_token = NULL,
    claim_until = NULL,
    last_error = NULL,
    sent_at = NULL,
    updated_at = excluded.updated_at
WHERE mailbox_egress.status = 'sent'
`

type InsertMailboxEgressParams struct {
	ID              string
	Connector       string
	LocalMailboxID  string
	RemoteMailboxID string
	RpcKind         string
	Service         string
	Method          string
	CorrelationID   sql.NullString
	ReplyTo         sql.NullString
	MsgID           string
	IdempotencyKey  string
	Envelope        []byte
	MaxAttempts     int32
	NextAttemptAt   int64
	CreatedAt       int64
}

func (q *Queries) InsertMailboxEgress(ctx context.Context, arg InsertMailboxEgressParams) error {
	_, err := q.db.ExecContext(ctx, InsertMailboxEgress,
		arg.ID,
		arg.Connector,
		arg.LocalMailboxID,
		arg.RemoteMailboxID,
		arg.RpcKind,
		arg.Service,
		arg.Method,
		arg.CorrelationID,
		arg.ReplyTo,
		arg.MsgID,
		arg.IdempotencyKey,
		arg.Envelope,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const ListDueMailboxEgressIDs = `-- name: ListDueMailboxEgressIDs :many
SELECT id
FROM mailbox_egress
WHERE next_attempt_at <= $1
  AND attempts < max_attempts
  AND (
    status = 'pending' OR
    (status = 'claimed' AND claim_until <= $1)
  )
ORDER BY next_attempt_at, created_at, id
LIMIT $2
`

type ListDueMailboxEgressIDsParams struct {
	NextAttemptAt int64
	Limit         int32
}

func (q *Queries) ListDueMailboxEgressIDs(ctx context.Context, arg ListDueMailboxEgressIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, ListDueMailboxEgressIDs, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkMailboxEgressSent = `-- name: MarkMailboxEgressSent :exec
UPDATE mailbox_egress
SET status = 'sent',
    sent_at = $3,
    updated_at = $3,
    claim_owner = NULL,
    claim_token = NULL,
    claim_until = NULL,
    last_error = NULL
WHERE id = $1
  AND claim_token = $2
  AND status = 'claimed'
`

type MarkMailboxEgressSentParams struct {
	ID         string
	ClaimToken sql.NullString
	SentAt     sql.NullInt64
}

func (q *Queries) MarkMailboxEgressSent(ctx context.Context, arg MarkMailboxEgressSentParams) error {
	_, err := q.db.ExecContext(ctx, MarkMailboxEgressSent, arg.ID, arg.ClaimToken, arg.SentAt)
	return err
}

const ReleaseExpiredMailboxEgressClaims = `-- name: ReleaseExpiredMailboxEgressClaims :exec
UPDATE mailbox_egress
SET status = 'pending',
    claim_owner = NULL,
    claim_token = NULL,
    claim_until = NULL,
    updated_at = $2
WHERE status = 'claimed'
  AND claim_until <= $1
`

type ReleaseExpiredMailboxEgressClaimsParams struct {
	ClaimUntil sql.NullInt64
	UpdatedAt  int64
}

func (q *Queries) ReleaseExpiredMailboxEgressClaims(ctx context.Context, arg ReleaseExpiredMailboxEgressClaimsParams) error {
	_, err := q.db.ExecContext(ctx, ReleaseExpiredMailboxEgressClaims, arg.ClaimUntil, arg.UpdatedAt)
	return err
}

const ReleaseMailboxEgressForRetry = `-- name: ReleaseMailboxEgressForRetry :exec
UPDATE mailbox_egress
SET status = CASE
        WHEN attempts >= max_attempts THEN 'dead'
        ELSE 'pending'
    END,
    next_attempt_at = $3,
    updated_at = $4,
    claim_owner = NULL,
    claim_token = NULL,
    claim_until = NULL,
    last_error = $5
WHERE id = $1
  AND claim_token = $2
  AND status = 'claimed'
`

type ReleaseMailboxEgressForRetryParams struct {
	ID            string
	ClaimToken    sql.NullString
	NextAttemptAt int64
	UpdatedAt     int64
	LastError     sql.NullString
}

func (q *Queries) ReleaseMailboxEgressForRetry(ctx context.Context, arg ReleaseMailboxEgressForRetryParams) error {
	_, err := q.db.ExecContext(ctx, ReleaseMailboxEgressForRetry,
		arg.ID,
		arg.ClaimToken,
		arg.NextAttemptAt,
		arg.UpdatedAt,
		arg.LastError,
	)
	return err
}

const UpsertMailboxIngressCursor = `-- name: UpsertMailboxIngressCursor :exec
INSERT INTO mailbox_ingress_cursors (
    local_mailbox_id, remote_mailbox_id, pull_cursor,
    dispatch_committed_to, ack_target, ack_committed_to,
    last_pull_at, last_dispatch_at, last_ack_at, last_error,
    created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12
)
ON CONFLICT (local_mailbox_id) DO UPDATE SET
    remote_mailbox_id = excluded.remote_mailbox_id,
    pull_cursor = excluded.pull_cursor,
    dispatch_committed_to = excluded.dispatch_committed_to,
    ack_target = excluded.ack_target,
    ack_committed_to = excluded.ack_committed_to,
    last_pull_at = excluded.last_pull_at,
    last_dispatch_at = excluded.last_dispatch_at,
    last_ack_at = excluded.last_ack_at,
    last_error = excluded.last_error,
    updated_at = excluded.updated_at
`

type UpsertMailboxIngressCursorParams struct {
	LocalMailboxID      string
	RemoteMailboxID     string
	PullCursor          int64
	DispatchCommittedTo int64
	AckTarget           int64
	AckCommittedTo      int64
	LastPullAt          sql.NullInt64
	LastDispatchAt      sql.NullInt64
	LastAckAt           sql.NullInt64
	LastError           sql.NullString
	CreatedAt           int64
	UpdatedAt           int64
}

func (q *Queries) UpsertMailboxIngressCursor(ctx context.Context, arg UpsertMailboxIngressCursorParams) error {
	_, err := q.db.ExecContext(ctx, UpsertMailboxIngressCursor,
		arg.LocalMailboxID,
		arg.RemoteMailboxID,
		arg.PullCursor,
		arg.DispatchCommittedTo,
		arg.AckTarget,
		arg.AckCommittedTo,
		arg.LastPullAt,
		arg.LastDispatchAt,
		arg.LastAckAt,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
