// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: unroll_jobs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const GetUnrollJob = `-- name: GetUnrollJob :one
SELECT target_outpoint_hash, target_outpoint_index, state, trigger, best_height, target_confirm_height, planner_state, deferred_checkpoints, sweep_tx, sweep_txid, sweep_confirm_height, sweep_attempts, fail_reason, created_at, updated_at FROM unroll_jobs
WHERE target_outpoint_hash = $1
  AND target_outpoint_index = $2
`

type GetUnrollJobParams struct {
	TargetOutpointHash  []byte
	TargetOutpointIndex int32
}

func (q *Queries) GetUnrollJob(ctx context.Context, arg GetUnrollJobParams) (UnrollJob, error) {
	row := q.db.QueryRowContext(ctx, GetUnrollJob, arg.TargetOutpointHash, arg.TargetOutpointIndex)
	var i UnrollJob
	err := row.Scan(
		&i.TargetOutpointHash,
		&i.TargetOutpointIndex,
		&i.State,
		&i.Trigger,
		&i.BestHeight,
		&i.TargetConfirmHeight,
		&i.PlannerState,
		&i.DeferredCheckpoints,
		&i.SweepTx,
		&i.SweepTxid,
		&i.SweepConfirmHeight,
		&i.SweepAttempts,
		&i.FailReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListNonTerminalUnrollJobs = `-- name: ListNonTerminalUnrollJobs :many
SELECT target_outpoint_hash, target_outpoint_index, state, trigger, best_height, target_confirm_height, planner_state, deferred_checkpoints, sweep_tx, sweep_txid, sweep_confirm_height, sweep_attempts, fail_reason, created_at, updated_at FROM unroll_jobs
WHERE state NOT IN ('completed', 'failed')
ORDER BY created_at ASC
`

func (q *Queries) ListNonTerminalUnrollJobs(ctx context.Context) ([]UnrollJob, error) {
	rows, err := q.db.QueryContext(ctx, ListNonTerminalUnrollJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnrollJob
	for rows.Next() {
		var i UnrollJob
		if err := rows.Scan(
			&i.TargetOutpointHash,
			&i.TargetOutpointIndex,
			&i.State,
			&i.Trigger,
			&i.BestHeight,
			&i.TargetConfirmHeight,
			&i.PlannerState,
			&i.DeferredCheckpoints,
			&i.SweepTx,
			&i.SweepTxid,
			&i.SweepConfirmHeight,
			&i.SweepAttempts,
			&i.FailReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkUnrollJobTerminal = `-- name: MarkUnrollJobTerminal :exec
UPDATE unroll_jobs
SET state = $3,
    fail_reason = $4,
    updated_at = $5,
    sweep_txid = $6
WHERE target_outpoint_hash = $1
  AND target_outpoint_index = $2
`

type MarkUnrollJobTerminalParams struct {
	TargetOutpointHash  []byte
	TargetOutpointIndex int32
	State               string
	FailReason          sql.NullString
	UpdatedAt           int64
	SweepTxid           []byte
}

func (q *Queries) MarkUnrollJobTerminal(ctx context.Context, arg MarkUnrollJobTerminalParams) error {
	_, err := q.db.ExecContext(ctx, MarkUnrollJobTerminal,
		arg.TargetOutpointHash,
		arg.TargetOutpointIndex,
		arg.State,
		arg.FailReason,
		arg.UpdatedAt,
		arg.SweepTxid,
	)
	return err
}

const UpsertUnrollJob = `-- name: UpsertUnrollJob :exec

INSERT INTO unroll_jobs (
    target_outpoint_hash, target_outpoint_index, state, trigger,
    best_height, target_confirm_height, planner_state, deferred_checkpoints,
    sweep_tx, sweep_txid, sweep_confirm_height, sweep_attempts, fail_reason,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (target_outpoint_hash, target_outpoint_index) DO UPDATE SET
    state = EXCLUDED.state,
    trigger = EXCLUDED.trigger,
    best_height = EXCLUDED.best_height,
    target_confirm_height = EXCLUDED.target_confirm_height,
    planner_state = EXCLUDED.planner_state,
    deferred_checkpoints = EXCLUDED.deferred_checkpoints,
    sweep_tx = EXCLUDED.sweep_tx,
    sweep_txid = EXCLUDED.sweep_txid,
    sweep_confirm_height = EXCLUDED.sweep_confirm_height,
    sweep_attempts = EXCLUDED.sweep_attempts,
    fail_reason = EXCLUDED.fail_reason,
    updated_at = EXCLUDED.updated_at
`

type UpsertUnrollJobParams struct {
	TargetOutpointHash  []byte
	TargetOutpointIndex int32
	State               string
	Trigger             string
	BestHeight          int32
	TargetConfirmHeight sql.NullInt32
	PlannerState        []byte
	DeferredCheckpoints []byte
	SweepTx             []byte
	SweepTxid           []byte
	SweepConfirmHeight  sql.NullInt32
	SweepAttempts       int32
	FailReason          sql.NullString
	CreatedAt           int64
	UpdatedAt           int64
}

// VTXO unroll job queries.
func (q *Queries) UpsertUnrollJob(ctx context.Context, arg UpsertUnrollJobParams) error {
	_, err := q.db.ExecContext(ctx, UpsertUnrollJob,
		arg.TargetOutpointHash,
		arg.TargetOutpointIndex,
		arg.State,
		arg.Trigger,
		arg.BestHeight,
		arg.TargetConfirmHeight,
		arg.PlannerState,
		arg.DeferredCheckpoints,
		arg.SweepTx,
		arg.SweepTxid,
		arg.SweepConfirmHeight,
		arg.SweepAttempts,
		arg.FailReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
