// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Acknowledge successful processing. Deletes the message.
	// Validates lease_token to prevent stale acks.
	AckMailboxMessage(ctx context.Context, arg AckMailboxMessageParams) (int64, error)
	// Claim a batch of pending outbox messages for delivery. Sets a claim token
	// and expiry to prevent concurrent publishers from processing the same messages.
	// Only selects rows that are unclaimed or whose claim has expired.
	ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]OutboxMessage, error)
	// Delete Ask results that have expired.
	CleanupExpiredAskResults(ctx context.Context, expiresAt int64) error
	// Delete expired deduplication entries.
	CleanupExpiredProcessedMessages(ctx context.Context, expiresAt int64) error
	// Delete dead letters older than a threshold.
	CleanupOldDeadLetters(ctx context.Context, createdAt int64) error
	// Mark an outbox message as successfully delivered. The claim token must match
	// to prevent stale publishers from completing messages they no longer own.
	CompleteOutboxMessage(ctx context.Context, arg CompleteOutboxMessageParams) error
	// Count total dead letters.
	CountDeadLetters(ctx context.Context) (int64, error)
	// Count pending messages for an actor's mailbox.
	CountPendingMailboxMessages(ctx context.Context, arg CountPendingMailboxMessagesParams) (int64, error)
	// Count pending outbox messages.
	CountPendingOutboxMessages(ctx context.Context) (int64, error)
	// Delete an Ask result after retrieval.
	DeleteAskResult(ctx context.Context, promiseID string) error
	// Delete a dead letter after manual processing.
	DeleteDeadLetter(ctx context.Context, id string) error
	// Delete an FSM checkpoint (e.g., when actor terminates normally).
	DeleteFSMCheckpoint(ctx context.Context, actorID string) error
	// Delete a mailbox message by ID (used after moving to dead letter).
	DeleteMailboxMessage(ctx context.Context, id string) error
	// Durable mailbox queries.
	// These queries support lease-based message delivery with exactly-once semantics.
	// =============================================================================
	// Mailbox Message Operations
	// =============================================================================
	// Enqueue a new message to an actor's mailbox.
	// ON CONFLICT (id) DO NOTHING enables receiver-side deduplication for outbox
	// delivery: if the OutboxPublisher successfully delivers a message but the
	// subsequent CompleteOutbox call fails, the retry will attempt to insert the
	// same outbox-derived ID. The conflict clause makes this a silent no-op
	// instead of an error, preserving exactly-once inbox semantics.
	EnqueueMailboxMessage(ctx context.Context, arg EnqueueMailboxMessageParams) error
	// =============================================================================
	// Outbox Operations (CDC Pattern)
	// =============================================================================
	// Enqueue a message to the transactional outbox.
	// Called within the same transaction as FSM state changes.
	EnqueueOutboxMessage(ctx context.Context, arg EnqueueOutboxMessageParams) error
	// Release all expired leases so messages can be redelivered.
	// Called periodically by a background cleanup task.
	ExpireMailboxLeases(ctx context.Context, leaseUntil sql.NullInt64) error
	// Extend the lease for long-running message processing.
	// Validates lease_token to prevent stale extensions.
	ExtendMailboxLease(ctx context.Context, arg ExtendMailboxLeaseParams) (int64, error)
	// Mark an outbox message as failed (dead letter). The claim token must match
	// to prevent stale publishers from failing messages they no longer own.
	FailOutboxMessage(ctx context.Context, arg FailOutboxMessageParams) error
	// Retrieve the result of an Ask message.
	GetAskResult(ctx context.Context, promiseID string) (AskResult, error)
	// =============================================================================
	// Dead Letter Operations
	// =============================================================================
	// Get a specific dead letter by ID.
	GetDeadLetter(ctx context.Context, id string) (DeadLetter, error)
	// Load an FSM checkpoint for an actor.
	GetFSMCheckpoint(ctx context.Context, actorID string) (FsmCheckpoint, error)
	// Get a specific mailbox message by ID.
	GetMailboxMessage(ctx context.Context, id string) (MailboxMessage, error)
	// Get a specific outbox message by ID.
	GetOutboxMessage(ctx context.Context, id string) (OutboxMessage, error)
	// =============================================================================
	// Ask Result Operations
	// =============================================================================
	// Store the result of an Ask message for caller retrieval.
	InsertAskResult(ctx context.Context, arg InsertAskResultParams) error
	// Check if a message has already been processed.
	IsMessageProcessed(ctx context.Context, id string) (bool, error)
	// Atomically claim the next available message for processing.
	// Sets lease_token and lease_until, increments attempts.
	// Returns NULL if no messages are available.
	// Ordering: priority DESC ensures high-priority (e.g., restart) messages first,
	// then available_at ASC for delivery order, then created_at ASC as a tiebreaker
	// to ensure deterministic ordering when priority and available_at are equal.
	LeaseNextMailboxMessage(ctx context.Context, arg LeaseNextMailboxMessageParams) (MailboxMessage, error)
	// List dead letters for a specific actor.
	ListDeadLettersByActor(ctx context.Context, arg ListDeadLettersByActorParams) ([]DeadLetter, error)
	// List dead letters by source type (mailbox or outbox).
	ListDeadLettersBySource(ctx context.Context, arg ListDeadLettersBySourceParams) ([]DeadLetter, error)
	// List all FSM checkpoints (for debugging/admin).
	ListFSMCheckpoints(ctx context.Context) ([]FsmCheckpoint, error)
	// List all messages for an actor's mailbox (for debugging).
	ListMailboxMessagesByActor(ctx context.Context, mailboxID string) ([]MailboxMessage, error)
	// List pending outbox messages for a specific target actor.
	ListPendingOutboxByTarget(ctx context.Context, targetActorID string) ([]OutboxMessage, error)
	// NOTE: DeleteOutboxMessage and CleanupCompletedOutbox are intentionally
	// omitted from this file. A dedicated GC procedure will be added in a
	// follow-up to handle cleanup of completed outbox messages and dead letters
	// with configurable retention policies.
	// =============================================================================
	// Processed Messages (Deduplication)
	// =============================================================================
	// Record that a message has been processed for deduplication.
	MarkMessageProcessed(ctx context.Context, arg MarkMessageProcessedParams) error
	// Move a failed message to the dead letter queue.
	MoveMailboxToDeadLetter(ctx context.Context, arg MoveMailboxToDeadLetterParams) error
	// Move a failed outbox message to the dead letter queue.
	MoveOutboxToDeadLetter(ctx context.Context, arg MoveOutboxToDeadLetterParams) error
	// Release message for redelivery after retry delay.
	// Clears lease and sets new available_at.
	// Validates lease_token to prevent stale nacks.
	NackMailboxMessage(ctx context.Context, arg NackMailboxMessageParams) (int64, error)
	// =============================================================================
	// FSM Checkpoints
	// =============================================================================
	// Save or update an FSM state checkpoint.
	SaveFSMCheckpoint(ctx context.Context, arg SaveFSMCheckpointParams) error
}

var _ Querier = (*Queries)(nil)
