package arkscript

import (
	"encoding/hex"
	"testing"

	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/txscript/v2"
	"github.com/lightninglabs/wavelength/internal/testutils"
	"github.com/stretchr/testify/require"
)

// GoldenVTXOVector contains the expected byte-for-byte output for a default
// VTXO template with specific inputs. These vectors ensure backward
// compatibility when refactoring the VTXO construction code.
type GoldenVTXOVector struct {
	// Name identifies this test vector.
	Name string

	// Inputs for VTXO construction.
	OwnerKeyIndex    int32
	OperatorKeyIndex int32
	ExitDelay        uint32

	// Expected outputs (hex encoded).
	OutputKeyHex      string
	CollabScriptHex   string
	TimeoutScriptHex  string
	CollabControlHex  string
	TimeoutControlHex string
	RootHashHex       string
	InternalKeyHex    string
}

// goldenVTXOVectors contains known-good test vectors generated from the
// current implementation. These MUST NOT be modified unless intentionally
// changing the VTXO output format (which would be a breaking change).
//
// Generated by TestGenerateGoldenVectors.
var goldenVTXOVectors = []GoldenVTXOVector{
	{
		Name:             "standard_vtxo_delay_100",
		OwnerKeyIndex:    1,
		OperatorKeyIndex: 2,
		ExitDelay:        100,
		OutputKeyHex: "034b1da83aada85e6879ef9b6b2d6cb0" +
			"a5ae6d6e4018514b4a1e20e54b7b79c5b5",
		CollabScriptHex: "20c6047f9441ed7d6d3045406e95c07c" +
			"d85c778e4b8cef3ca7abac09b95c709ee5ad20" +
			"f9308a019258c31049344f85f89d5229b531c8" +
			"45836f99b08601f113bce036f9ac",
		TimeoutScriptHex: "20c6047f9441ed7d6d3045406e95c0" +
			"7cd85c778e4b8cef3ca7abac09b95c709ee5" +
			"ac0164b275",
		CollabControlHex: "c1372f225b3caee8213096de3229ee" +
			"4335306b07c3c169438461b5d4749884ec65" +
			"768dc7e0689a1fa760492e409e1a71d25122" +
			"742802d845c745eb466536e5a379",
		TimeoutControlHex: "c1372f225b3caee8213096de3229e" +
			"e4335306b07c3c169438461b5d4749884ec" +
			"65c9bcb65c1015db6b44e5c2977606cf7a5" +
			"d8f13d226531c6d01133d0810bed17b",
		RootHashHex: "9556f4e03cfb047183ca430d888510c8" +
			"1f85d2900f27e6edfbfbe3d257a18449",
		InternalKeyHex: "02372f225b3caee8213096de3229ee43" +
			"35306b07c3c169438461b5d4749884ec65",
	},
	{
		Name:             "standard_vtxo_delay_144",
		OwnerKeyIndex:    1,
		OperatorKeyIndex: 2,
		ExitDelay:        144,
		OutputKeyHex: "0300c079f74ac147b723b3521be6135e" +
			"be384a43d00c80250d723ec362ed7d0dbb",
		CollabScriptHex: "20c6047f9441ed7d6d3045406e95c07c" +
			"d85c778e4b8cef3ca7abac09b95c709ee5ad20" +
			"f9308a019258c31049344f85f89d5229b531c8" +
			"45836f99b08601f113bce036f9ac",
		TimeoutScriptHex: "20c6047f9441ed7d6d3045406e95c0" +
			"7cd85c778e4b8cef3ca7abac09b95c709ee5" +
			"ac029000b275",
		CollabControlHex: "c1372f225b3caee8213096de3229ee" +
			"4335306b07c3c169438461b5d4749884ec65" +
			"516418a4dcdd5aede804a44a350d34a1dcfc" +
			"1710a831ad7dcf22ede841109e21",
		TimeoutControlHex: "c1372f225b3caee8213096de3229e" +
			"e4335306b07c3c169438461b5d4749884ec" +
			"65c9bcb65c1015db6b44e5c2977606cf7a5" +
			"d8f13d226531c6d01133d0810bed17b",
		RootHashHex: "b5b4967c4c6498176fa9efe0dfb93b0f" +
			"86e353ae4754c8d74c8924af966aa4c8",
		InternalKeyHex: "02372f225b3caee8213096de3229ee43" +
			"35306b07c3c169438461b5d4749884ec65",
	},
	{
		Name:             "different_keys_delay_1000",
		OwnerKeyIndex:    3,
		OperatorKeyIndex: 4,
		ExitDelay:        1000,
		OutputKeyHex: "03d0aa1582ee548fbd843b033e825505" +
			"044b4c140d04c43eaf1ae79644cebec1ce",
		CollabScriptHex: "20e493dbf1c10d80f3581e4904930b14" +
			"04cc6c13900ee0758474fa94abe8c4cd13ad20" +
			"2f8bde4d1a07209355b4a7250a5c5128e88b84" +
			"bddc619ab7cba8d569b240efe4ac",
		TimeoutScriptHex: "20e493dbf1c10d80f3581e4904930b" +
			"1404cc6c13900ee0758474fa94abe8c4cd13" +
			"ac02e803b275",
		CollabControlHex: "c1372f225b3caee8213096de3229ee" +
			"4335306b07c3c169438461b5d4749884ec65" +
			"cbffc64f760572022a8b0d69c3ece570db0c" +
			"0b1f91e28729aaa8df5fabe91941",
		TimeoutControlHex: "c1372f225b3caee8213096de3229e" +
			"e4335306b07c3c169438461b5d4749884ec" +
			"65f0bc64ae7445c4a5cf0f5a8acd2c0fa34" +
			"1dc3708597002c09d051e7d8bfe1ed4",
		RootHashHex: "70550fd4a23331f6c0b1d9c56a05d8f9" +
			"7b60e686ed5198eb7597f9b0c1240aa8",
		InternalKeyHex: "02372f225b3caee8213096de3229ee43" +
			"35306b07c3c169438461b5d4749884ec65",
	},
}

// TestGoldenVTXOVectors validates that the current VTXO implementation
// produces byte-identical output to the golden vectors. This test MUST pass
// before and after any refactoring of the VTXO construction code.
func TestGoldenVTXOVectors(t *testing.T) {
	t.Parallel()

	for _, vec := range goldenVTXOVectors {
		t.Run(vec.Name, func(t *testing.T) {
			t.Parallel()

			// Generate keys using the same deterministic method.
			ownerKey, _ := testutils.CreateKey(vec.OwnerKeyIndex)
			operatorKey, _ := testutils.CreateKey(
				vec.OperatorKeyIndex,
			)

			// Create the VTXO tapscript.
			tapscript, err := VTXOTapScript(
				ownerKey, operatorKey, vec.ExitDelay,
			)
			require.NoError(t, err)

			// Verify internal key is the NUMS key.
			require.Equal(
				t, ARKNUMSKey.SerializeCompressed(),
				tapscript.ControlBlock.InternalKey.
					SerializeCompressed(),
				"internal key should be NUMS key",
			)

			// Verify root hash matches.
			rootHashHex := hex.EncodeToString(tapscript.RootHash)
			require.Equal(
				t, vec.RootHashHex, rootHashHex,
				"root hash mismatch",
			)

			// Verify output key matches.
			outputKey, err := tapscript.TaprootKey()
			require.NoError(t, err)
			outputKeyHex := hex.EncodeToString(
				outputKey.SerializeCompressed(),
			)
			require.Equal(
				t, vec.OutputKeyHex, outputKeyHex,
				"output key mismatch",
			)

			// Verify collab leaf script matches (index 0).
			require.Len(
				t, tapscript.Leaves, 2,
				"expected exactly 2 leaves",
			)
			collabScriptHex := hex.EncodeToString(
				tapscript.Leaves[0].Script,
			)
			require.Equal(
				t, vec.CollabScriptHex, collabScriptHex,
				"collab script mismatch",
			)

			// Verify timeout leaf script matches (index 1).
			timeoutScriptHex := hex.EncodeToString(
				tapscript.Leaves[1].Script,
			)
			require.Equal(
				t, vec.TimeoutScriptHex, timeoutScriptHex,
				"timeout script mismatch",
			)

			// Verify control blocks match via policy API.
			policy, err := NewVTXOPolicy(
				ownerKey, operatorKey, vec.ExitDelay,
			)
			require.NoError(t, err)

			collabInfo, err := policy.CollabSpendInfo()
			require.NoError(t, err)
			collabControlHex := hex.EncodeToString(
				collabInfo.ControlBlock,
			)
			require.Equal(
				t, vec.CollabControlHex, collabControlHex,
				"collab control block mismatch",
			)

			exitInfo, err := policy.ExitSpendInfo()
			require.NoError(t, err)
			timeoutControlHex := hex.EncodeToString(
				exitInfo.ControlBlock,
			)
			require.Equal(
				t, vec.TimeoutControlHex, timeoutControlHex,
				"timeout control block mismatch",
			)
		})
	}
}

// TestGenerateGoldenVectors generates golden vectors from the current
// implementation. Run this test to update the hardcoded vectors above when
// intentionally changing the VTXO format.
//
// Usage: go test -v -run TestGenerateGoldenVectors.
func TestGenerateGoldenVectors(t *testing.T) {
	// Skip by default since this is a generator, not a validator.
	if testing.Short() {
		t.Skip("skipping vector generation in short mode")
	}

	testCases := []struct {
		name             string
		ownerKeyIndex    int32
		operatorKeyIndex int32
		exitDelay        uint32
	}{
		{
			name:             "standard_vtxo_delay_100",
			ownerKeyIndex:    1,
			operatorKeyIndex: 2,
			exitDelay:        100,
		},
		{
			name:             "standard_vtxo_delay_144",
			ownerKeyIndex:    1,
			operatorKeyIndex: 2,
			exitDelay:        144,
		},
		{
			name:             "different_keys_delay_1000",
			ownerKeyIndex:    3,
			operatorKeyIndex: 4,
			exitDelay:        1000,
		},
	}

	t.Log("Generated Golden Vectors (copy to goldenVTXOVectors):")
	t.Log("")

	for _, tc := range testCases {
		ownerKey, _ := testutils.CreateKey(tc.ownerKeyIndex)
		operatorKey, _ := testutils.CreateKey(tc.operatorKeyIndex)

		tapscript, err := VTXOTapScript(
			ownerKey, operatorKey, tc.exitDelay,
		)
		require.NoError(t, err)

		outputKey, err := tapscript.TaprootKey()
		require.NoError(t, err)

		// Build tap tree to get control blocks.
		tree := txscript.AssembleTaprootScriptTree(tapscript.Leaves...)

		collabProof := tree.LeafMerkleProofs[0]
		collabControl := collabProof.ToControlBlock(
			tapscript.ControlBlock.InternalKey,
		)
		collabControlBytes, err := collabControl.ToBytes()
		require.NoError(t, err)

		timeoutProof := tree.LeafMerkleProofs[1]
		timeoutControl := timeoutProof.ToControlBlock(
			tapscript.ControlBlock.InternalKey,
		)
		timeoutControlBytes, err := timeoutControl.ToBytes()
		require.NoError(t, err)

		t.Logf(`{
	Name:             %q,
	OwnerKeyIndex:    %d,
	OperatorKeyIndex: %d,
	ExitDelay:        %d,
	OutputKeyHex:      %q,
	CollabScriptHex:   %q,
	TimeoutScriptHex:  %q,
	CollabControlHex:  %q,
	TimeoutControlHex: %q,
	RootHashHex:       %q,
	InternalKeyHex:    %q,
},`,
			tc.name,
			tc.ownerKeyIndex,
			tc.operatorKeyIndex,
			tc.exitDelay,
			hex.EncodeToString(outputKey.SerializeCompressed()),
			hex.EncodeToString(tapscript.Leaves[0].Script),
			hex.EncodeToString(tapscript.Leaves[1].Script),
			hex.EncodeToString(collabControlBytes),
			hex.EncodeToString(timeoutControlBytes),
			hex.EncodeToString(tapscript.RootHash),
			hex.EncodeToString(
				tapscript.ControlBlock.InternalKey.
					SerializeCompressed(),
			),
		)
		t.Log("")
	}
}

// TestVTXOScriptStructure validates the structure of VTXO scripts matches
// the RFC specification. This documents the expected script format.
func TestVTXOScriptStructure(t *testing.T) {
	t.Parallel()

	ownerKey, _ := testutils.CreateKey(1)
	operatorKey, _ := testutils.CreateKey(2)
	exitDelay := uint32(100)

	tapscript, err := VTXOTapScript(ownerKey, operatorKey, exitDelay)
	require.NoError(t, err)

	// Verify we have exactly 2 leaves.
	require.Len(t, tapscript.Leaves, 2)

	// Leaf 0: Collaborative multisig (collab).
	// Expected format:
	// <owner_key> CHECKSIGVERIFY <operator_key> CHECKSIG.
	collabScript := tapscript.Leaves[0].Script
	t.Logf(
		"Collab script (%d bytes): %s", len(collabScript),
		disassemble(t, collabScript),
	)

	// Leaf 1: Timeout/exit path (CSV-gated single sig).
	// Expected format: <owner_key> OP_CHECKSIG <delay> OP_CSV OP_DROP
	timeoutScript := tapscript.Leaves[1].Script
	t.Logf(
		"Timeout script (%d bytes): %s", len(timeoutScript),
		disassemble(t, timeoutScript),
	)

	// Verify internal key is the NUMS key.
	require.Equal(
		t, ARKNUMSKey.SerializeCompressed(),
		tapscript.ControlBlock.InternalKey.SerializeCompressed(),
		"internal key should be NUMS key",
	)

	// Verify leaf version is base tapscript version.
	require.Equal(
		t, txscript.BaseLeafVersion, tapscript.Leaves[0].LeafVersion,
		"collab leaf should use base version",
	)
	require.Equal(
		t, txscript.BaseLeafVersion, tapscript.Leaves[1].LeafVersion,
		"timeout leaf should use base version",
	)
}

// disassemble returns a human-readable disassembly of a script.
func disassemble(t *testing.T, script []byte) string {
	t.Helper()
	dis, err := txscript.DisasmString(script)
	require.NoError(t, err)

	return dis
}

// TestNUMSKeyConsistency verifies the NUMS key is consistent.
func TestNUMSKeyConsistency(t *testing.T) {
	t.Parallel()

	// The NUMS key should match the documented value.
	expectedHex := "02372f225b3caee8213096de3229ee43" +
		"35306b07c3c169438461b5d4749884ec65"
	actualHex := hex.EncodeToString(ARKNUMSKey.SerializeCompressed())
	require.Equal(t, expectedHex, actualHex, "NUMS key mismatch")

	// Verify the key is a valid point on the curve.
	keyBytes, err := hex.DecodeString(expectedHex)
	require.NoError(t, err)

	pubKey, err := btcec.ParsePubKey(keyBytes)
	require.NoError(t, err)
	require.NotNil(t, pubKey)

	// The key should match when re-serialized.
	require.Equal(t, keyBytes, pubKey.SerializeCompressed())
}
