// Code generated by protoc-gen-mailboxrpc. DO NOT EDIT.

package arkrpc

import (
	context "context"
	fmt "fmt"
	rpc "github.com/lightninglabs/wavelength/mailbox/rpc"
	proto "google.golang.org/protobuf/proto"
)

// ArkServiceMailboxClient is a typed mailbox RPC client for ArkService.
type ArkServiceMailboxClient struct {
	// C is the underlying RPC-over-mailbox runtime client.
	C rpc.RPCClient
}

// NewArkServiceMailboxClient creates a typed mailbox client.
func NewArkServiceMailboxClient(c rpc.RPCClient) *ArkServiceMailboxClient {
	return &ArkServiceMailboxClient{
		C: c,
	}
}

// ArkServiceMailboxServer is the mailbox server interface for ArkService.
type ArkServiceMailboxServer interface {
	// GetInfo handles GetInfo.
	GetInfo(ctx context.Context, req *GetInfoRequest) (*GetInfoResponse, error)
	// EstimateFee handles EstimateFee.
	EstimateFee(ctx context.Context, req *EstimateFeeRequest) (*EstimateFeeResponse, error)
	// RegisterVirtualChannel handles RegisterVirtualChannel.
	RegisterVirtualChannel(ctx context.Context, req *RegisterVirtualChannelRequest) (*RegisterVirtualChannelResponse, error)
	// ActivateVirtualChannel handles ActivateVirtualChannel.
	ActivateVirtualChannel(ctx context.Context, req *ActivateVirtualChannelRequest) (*ActivateVirtualChannelResponse, error)
	// CosignVirtualChannelBacking handles CosignVirtualChannelBacking.
	CosignVirtualChannelBacking(ctx context.Context, req *CosignVirtualChannelBackingRequest) (*CosignVirtualChannelBackingResponse, error)
	// RequestVirtualChannelIntent handles RequestVirtualChannelIntent.
	RequestVirtualChannelIntent(ctx context.Context, req *RequestVirtualChannelIntentRequest) (*RequestVirtualChannelIntentResponse, error)
}

// RegisterArkServiceMailboxServer registers handlers for ArkService.
func RegisterArkServiceMailboxServer(r rpc.Router, impl ArkServiceMailboxServer) {
	r.Handle("arkrpc.ArkService", "GetInfo", func() proto.Message {
		return &GetInfoRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*GetInfoRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.GetInfo(ctx, req)
	})
	r.Handle("arkrpc.ArkService", "EstimateFee", func() proto.Message {
		return &EstimateFeeRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*EstimateFeeRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.EstimateFee(ctx, req)
	})
	r.Handle("arkrpc.ArkService", "RegisterVirtualChannel", func() proto.Message {
		return &RegisterVirtualChannelRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*RegisterVirtualChannelRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.RegisterVirtualChannel(ctx, req)
	})
	r.Handle("arkrpc.ArkService", "ActivateVirtualChannel", func() proto.Message {
		return &ActivateVirtualChannelRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ActivateVirtualChannelRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ActivateVirtualChannel(ctx, req)
	})
	r.Handle("arkrpc.ArkService", "CosignVirtualChannelBacking", func() proto.Message {
		return &CosignVirtualChannelBackingRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*CosignVirtualChannelBackingRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.CosignVirtualChannelBacking(ctx, req)
	})
	r.Handle("arkrpc.ArkService", "RequestVirtualChannelIntent", func() proto.Message {
		return &RequestVirtualChannelIntentRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*RequestVirtualChannelIntentRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.RequestVirtualChannelIntent(ctx, req)
	})
}

// GetInfo calls the GetInfo RPC.
func (c *ArkServiceMailboxClient) GetInfo(ctx context.Context, req *GetInfoRequest, opts ...rpc.RPCOptions) (*GetInfoResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.ArkService",
		Method:  "GetInfo",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(GetInfoResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// EstimateFee calls the EstimateFee RPC.
func (c *ArkServiceMailboxClient) EstimateFee(ctx context.Context, req *EstimateFeeRequest, opts ...rpc.RPCOptions) (*EstimateFeeResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.ArkService",
		Method:  "EstimateFee",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(EstimateFeeResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// RegisterVirtualChannel calls the RegisterVirtualChannel RPC.
func (c *ArkServiceMailboxClient) RegisterVirtualChannel(ctx context.Context, req *RegisterVirtualChannelRequest, opts ...rpc.RPCOptions) (*RegisterVirtualChannelResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.ArkService",
		Method:  "RegisterVirtualChannel",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(RegisterVirtualChannelResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ActivateVirtualChannel calls the ActivateVirtualChannel RPC.
func (c *ArkServiceMailboxClient) ActivateVirtualChannel(ctx context.Context, req *ActivateVirtualChannelRequest, opts ...rpc.RPCOptions) (*ActivateVirtualChannelResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.ArkService",
		Method:  "ActivateVirtualChannel",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(ActivateVirtualChannelResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// CosignVirtualChannelBacking calls the CosignVirtualChannelBacking RPC.
func (c *ArkServiceMailboxClient) CosignVirtualChannelBacking(ctx context.Context, req *CosignVirtualChannelBackingRequest, opts ...rpc.RPCOptions) (*CosignVirtualChannelBackingResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.ArkService",
		Method:  "CosignVirtualChannelBacking",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(CosignVirtualChannelBackingResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// RequestVirtualChannelIntent calls the RequestVirtualChannelIntent RPC.
func (c *ArkServiceMailboxClient) RequestVirtualChannelIntent(ctx context.Context, req *RequestVirtualChannelIntentRequest, opts ...rpc.RPCOptions) (*RequestVirtualChannelIntentResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.ArkService",
		Method:  "RequestVirtualChannelIntent",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(RequestVirtualChannelIntentResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
