// Code generated by protoc-gen-mailboxrpc. DO NOT EDIT.

package arkrpc

import (
	context "context"
	fmt "fmt"
	rpc "github.com/lightninglabs/wavelength/mailbox/rpc"
	proto "google.golang.org/protobuf/proto"
)

// IndexerServiceMailboxClient is a typed mailbox RPC client for IndexerService.
type IndexerServiceMailboxClient struct {
	// C is the underlying RPC-over-mailbox runtime client.
	C rpc.RPCClient
}

// NewIndexerServiceMailboxClient creates a typed mailbox client.
func NewIndexerServiceMailboxClient(c rpc.RPCClient) *IndexerServiceMailboxClient {
	return &IndexerServiceMailboxClient{
		C: c,
	}
}

// IndexerServiceMailboxServer is the mailbox server interface for IndexerService.
type IndexerServiceMailboxServer interface {
	// RegisterReceiveScript handles RegisterReceiveScript.
	RegisterReceiveScript(ctx context.Context, req *RegisterReceiveScriptRequest) (*RegisterReceiveScriptResponse, error)
	// ListMyReceiveScripts handles ListMyReceiveScripts.
	ListMyReceiveScripts(ctx context.Context, req *ListMyReceiveScriptsRequest) (*ListMyReceiveScriptsResponse, error)
	// UnregisterReceiveScript handles UnregisterReceiveScript.
	UnregisterReceiveScript(ctx context.Context, req *UnregisterReceiveScriptRequest) (*UnregisterReceiveScriptResponse, error)
	// ListOORRecipientEventsByScript handles ListOORRecipientEventsByScript.
	ListOORRecipientEventsByScript(ctx context.Context, req *ListOORRecipientEventsByScriptRequest) (*ListOORRecipientEventsByScriptResponse, error)
	// ListVTXOsByScripts handles ListVTXOsByScripts.
	ListVTXOsByScripts(ctx context.Context, req *ListVTXOsByScriptsRequest) (*ListVTXOsByScriptsResponse, error)
	// GetOORSessionByTxid handles GetOORSessionByTxid.
	GetOORSessionByTxid(ctx context.Context, req *GetOORSessionByTxidRequest) (*GetOORSessionByTxidResponse, error)
	// GetSubtreeByScripts handles GetSubtreeByScripts.
	GetSubtreeByScripts(ctx context.Context, req *GetSubtreeByScriptsRequest) (*GetSubtreeByScriptsResponse, error)
	// ListVTXOEventsByScripts handles ListVTXOEventsByScripts.
	ListVTXOEventsByScripts(ctx context.Context, req *ListVTXOEventsByScriptsRequest) (*ListVTXOEventsByScriptsResponse, error)
}

// RegisterIndexerServiceMailboxServer registers handlers for IndexerService.
func RegisterIndexerServiceMailboxServer(r rpc.Router, impl IndexerServiceMailboxServer) {
	r.Handle("arkrpc.IndexerService", "RegisterReceiveScript", func() proto.Message {
		return &RegisterReceiveScriptRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*RegisterReceiveScriptRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.RegisterReceiveScript(ctx, req)
	})
	r.Handle("arkrpc.IndexerService", "ListMyReceiveScripts", func() proto.Message {
		return &ListMyReceiveScriptsRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ListMyReceiveScriptsRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ListMyReceiveScripts(ctx, req)
	})
	r.Handle("arkrpc.IndexerService", "UnregisterReceiveScript", func() proto.Message {
		return &UnregisterReceiveScriptRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*UnregisterReceiveScriptRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.UnregisterReceiveScript(ctx, req)
	})
	r.Handle("arkrpc.IndexerService", "ListOORRecipientEventsByScript", func() proto.Message {
		return &ListOORRecipientEventsByScriptRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ListOORRecipientEventsByScriptRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ListOORRecipientEventsByScript(ctx, req)
	})
	r.Handle("arkrpc.IndexerService", "ListVTXOsByScripts", func() proto.Message {
		return &ListVTXOsByScriptsRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ListVTXOsByScriptsRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ListVTXOsByScripts(ctx, req)
	})
	r.Handle("arkrpc.IndexerService", "GetOORSessionByTxid", func() proto.Message {
		return &GetOORSessionByTxidRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*GetOORSessionByTxidRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.GetOORSessionByTxid(ctx, req)
	})
	r.Handle("arkrpc.IndexerService", "GetSubtreeByScripts", func() proto.Message {
		return &GetSubtreeByScriptsRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*GetSubtreeByScriptsRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.GetSubtreeByScripts(ctx, req)
	})
	r.Handle("arkrpc.IndexerService", "ListVTXOEventsByScripts", func() proto.Message {
		return &ListVTXOEventsByScriptsRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ListVTXOEventsByScriptsRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ListVTXOEventsByScripts(ctx, req)
	})
}

// RegisterReceiveScript calls the RegisterReceiveScript RPC.
func (c *IndexerServiceMailboxClient) RegisterReceiveScript(ctx context.Context, req *RegisterReceiveScriptRequest, opts ...rpc.RPCOptions) (*RegisterReceiveScriptResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "RegisterReceiveScript",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(RegisterReceiveScriptResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ListMyReceiveScripts calls the ListMyReceiveScripts RPC.
func (c *IndexerServiceMailboxClient) ListMyReceiveScripts(ctx context.Context, req *ListMyReceiveScriptsRequest, opts ...rpc.RPCOptions) (*ListMyReceiveScriptsResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "ListMyReceiveScripts",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(ListMyReceiveScriptsResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// UnregisterReceiveScript calls the UnregisterReceiveScript RPC.
func (c *IndexerServiceMailboxClient) UnregisterReceiveScript(ctx context.Context, req *UnregisterReceiveScriptRequest, opts ...rpc.RPCOptions) (*UnregisterReceiveScriptResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "UnregisterReceiveScript",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(UnregisterReceiveScriptResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ListOORRecipientEventsByScript calls the ListOORRecipientEventsByScript RPC.
func (c *IndexerServiceMailboxClient) ListOORRecipientEventsByScript(ctx context.Context, req *ListOORRecipientEventsByScriptRequest, opts ...rpc.RPCOptions) (*ListOORRecipientEventsByScriptResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "ListOORRecipientEventsByScript",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(ListOORRecipientEventsByScriptResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ListVTXOsByScripts calls the ListVTXOsByScripts RPC.
func (c *IndexerServiceMailboxClient) ListVTXOsByScripts(ctx context.Context, req *ListVTXOsByScriptsRequest, opts ...rpc.RPCOptions) (*ListVTXOsByScriptsResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "ListVTXOsByScripts",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(ListVTXOsByScriptsResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// GetOORSessionByTxid calls the GetOORSessionByTxid RPC.
func (c *IndexerServiceMailboxClient) GetOORSessionByTxid(ctx context.Context, req *GetOORSessionByTxidRequest, opts ...rpc.RPCOptions) (*GetOORSessionByTxidResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "GetOORSessionByTxid",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(GetOORSessionByTxidResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// GetSubtreeByScripts calls the GetSubtreeByScripts RPC.
func (c *IndexerServiceMailboxClient) GetSubtreeByScripts(ctx context.Context, req *GetSubtreeByScriptsRequest, opts ...rpc.RPCOptions) (*GetSubtreeByScriptsResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "GetSubtreeByScripts",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(GetSubtreeByScriptsResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ListVTXOEventsByScripts calls the ListVTXOEventsByScripts RPC.
func (c *IndexerServiceMailboxClient) ListVTXOEventsByScripts(ctx context.Context, req *ListVTXOEventsByScriptsRequest, opts ...rpc.RPCOptions) (*ListVTXOEventsByScriptsResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "arkrpc.IndexerService",
		Method:  "ListVTXOEventsByScripts",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(ListVTXOEventsByScriptsResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
