// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type PaySwap struct {
	PaymentHash                          []byte
	Invoice                              string
	MaxFeeSat                            int64
	State                                string
	AmountSat                            int64
	FeeSat                               int64
	ExpiryUnix                           int64
	ClientPubkey                         []byte
	OperatorPubkey                       []byte
	ServerPubkey                         []byte
	RefundLocktime                       int64
	UnilateralClaimDelay                 int64
	UnilateralRefundDelay                int64
	UnilateralRefundWithoutReceiverDelay int64
	VhtlcPkscript                        []byte
	VhtlcPolicyTemplate                  []byte
	VhtlcOutpoint                        string
	VhtlcAmount                          int64
	FundingSessionID                     string
	RefundReceivePubkey                  []byte
	RefundReceivePkscript                []byte
	RefundSessionID                      string
	RefundRecoveryID                     string
	Preimage                             []byte
	InterventionReason                   string
	CreatedAtUnix                        int64
	UpdatedAtUnix                        int64
	SettlementType                       string
}

type ReceiveSwap struct {
	PaymentHash                          []byte
	AmountSat                            int64
	PayerFeeMsat                         int64
	State                                string
	Invoice                              string
	Preimage                             []byte
	DeadlineUnix                         int64
	ClientPubkey                         []byte
	PaymentAddr                          []byte
	OperatorPubkey                       []byte
	SwapServerPubkey                     []byte
	RefundLocktime                       int64
	UnilateralClaimDelay                 int64
	UnilateralRefundDelay                int64
	UnilateralRefundWithoutReceiverDelay int64
	VhtlcPkscript                        []byte
	VhtlcPolicyTemplate                  []byte
	VhtlcOutpoint                        string
	VhtlcAmount                          int64
	PendingHtlcAckCursor                 int64
	ClaimReceivePubkey                   []byte
	ClaimReceivePkscript                 []byte
	ClaimSessionID                       string
	ClaimRecoveryID                      string
	InterventionReason                   string
	CreatedAtUnix                        int64
	UpdatedAtUnix                        int64
	SettlementType                       string
	RequestedAmountSat                   int64
	AvailableCreditSat                   int64
	AttachedCreditSat                    int64
	DustLimitSat                         int64
}

type RefreshSwap struct {
	PaymentHash                                []byte
	Preimage                                   []byte
	AmountSat                                  int64
	SourceOutpoint                             string
	MaxVtxoAgeBlocks                           int64
	State                                      string
	StateVersion                               int64
	ExpiryUnix                                 int64
	ClientPubkey                               []byte
	OperatorPubkey                             []byte
	ServerPubkey                               []byte
	SettlementType                             string
	InputRefundLocktime                        int64
	InputUnilateralClaimDelay                  int64
	InputUnilateralRefundDelay                 int64
	InputUnilateralRefundWithoutReceiverDelay  int64
	InputVhtlcPkscript                         []byte
	InputVhtlcPolicyTemplate                   []byte
	InputVhtlcOutpoint                         string
	InputVhtlcAmount                           int64
	FundingSessionID                           string
	InputRefundReceivePubkey                   []byte
	InputRefundReceivePkscript                 []byte
	InputRefundSessionID                       string
	InputRefundRecoveryID                      string
	OutputSenderPubkey                         []byte
	OutputRefundLocktime                       int64
	OutputUnilateralClaimDelay                 int64
	OutputUnilateralRefundDelay                int64
	OutputUnilateralRefundWithoutReceiverDelay int64
	OutputVhtlcPkscript                        []byte
	OutputVhtlcPolicyTemplate                  []byte
	OutputVhtlcOutpoint                        string
	OutputVhtlcAmount                          int64
	OutputObservedHeight                       int64
	OutputCreatedHeight                        int64
	OutputBatchExpiry                          int64
	PendingHtlcAckCursor                       int64
	OutputClaimReceivePubkey                   []byte
	OutputClaimReceivePkscript                 []byte
	OutputClaimSessionID                       string
	OutputClaimRecoveryID                      string
	InputClaimTxid                             string
	InterventionReason                         string
	CreatedAtUnix                              int64
	UpdatedAtUnix                              int64
}

type SwapHashOwner struct {
	PaymentHash []byte
	Direction   string
}
