// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type PaySwap struct {
	PaymentHash                          []byte
	Invoice                              string
	MaxFeeSat                            int64
	State                                string
	AmountSat                            int64
	FeeSat                               int64
	ExpiryUnix                           int64
	ClientPubkey                         []byte
	OperatorPubkey                       []byte
	ServerPubkey                         []byte
	RefundLocktime                       int64
	UnilateralClaimDelay                 int64
	UnilateralRefundDelay                int64
	UnilateralRefundWithoutReceiverDelay int64
	VhtlcPkscript                        []byte
	VhtlcPolicyTemplate                  []byte
	VhtlcOutpoint                        string
	VhtlcAmount                          int64
	FundingSessionID                     string
	RefundReceivePubkey                  []byte
	RefundReceivePkscript                []byte
	RefundSessionID                      string
	Preimage                             []byte
	InterventionReason                   string
	CreatedAtUnix                        int64
	UpdatedAtUnix                        int64
}

type ReceiveAuthKey struct {
	KeyID         string
	PrivateKey    []byte
	CreatedAtUnix int64
}

type ReceiveSwap struct {
	PaymentHash                          []byte
	AmountSat                            int64
	State                                string
	Invoice                              string
	Preimage                             []byte
	DeadlineUnix                         int64
	ClientPubkey                         []byte
	PaymentAddr                          []byte
	OperatorPubkey                       []byte
	SwapServerPubkey                     []byte
	RefundLocktime                       int64
	UnilateralClaimDelay                 int64
	UnilateralRefundDelay                int64
	UnilateralRefundWithoutReceiverDelay int64
	VhtlcPkscript                        []byte
	VhtlcPolicyTemplate                  []byte
	VhtlcOutpoint                        string
	VhtlcAmount                          int64
	PendingHtlcAckCursor                 int64
	ClaimSessionID                       string
	InterventionReason                   string
	CreatedAtUnix                        int64
	UpdatedAtUnix                        int64
}
