// Code generated by protoc-gen-mailboxrpc. DO NOT EDIT.

package hellotestpb

import (
	context "context"
	fmt "fmt"
	rpc "github.com/lightninglabs/wavelength/mailbox/rpc"
	proto "google.golang.org/protobuf/proto"
)

// HelloServiceMailboxClient is a typed mailbox RPC client for HelloService.
type HelloServiceMailboxClient struct {
	// C is the underlying RPC-over-mailbox runtime client.
	C rpc.RPCClient
}

// NewHelloServiceMailboxClient creates a typed mailbox client.
func NewHelloServiceMailboxClient(c rpc.RPCClient) *HelloServiceMailboxClient {
	return &HelloServiceMailboxClient{
		C: c,
	}
}

// HelloServiceMailboxServer is the mailbox server interface for HelloService.
type HelloServiceMailboxServer interface {
	// SayHello handles SayHello.
	SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error)
	// SayGoodbye handles SayGoodbye.
	SayGoodbye(ctx context.Context, req *GoodbyeRequest) (*GoodbyeResponse, error)
}

// RegisterHelloServiceMailboxServer registers handlers for HelloService.
func RegisterHelloServiceMailboxServer(r rpc.Router, impl HelloServiceMailboxServer) {
	r.Handle("hellotest.v1.HelloService", "SayHello", func() proto.Message {
		return &HelloRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*HelloRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SayHello(ctx, req)
	})
	r.Handle("hellotest.v1.HelloService", "SayGoodbye", func() proto.Message {
		return &GoodbyeRequest{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*GoodbyeRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SayGoodbye(ctx, req)
	})
}

// SayHello calls the SayHello RPC.
func (c *HelloServiceMailboxClient) SayHello(ctx context.Context, req *HelloRequest, opts ...rpc.RPCOptions) (*HelloResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "hellotest.v1.HelloService",
		Method:  "SayHello",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(HelloResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SayGoodbye calls the SayGoodbye RPC.
func (c *HelloServiceMailboxClient) SayGoodbye(ctx context.Context, req *GoodbyeRequest, opts ...rpc.RPCOptions) (*GoodbyeResponse, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "hellotest.v1.HelloService",
		Method:  "SayGoodbye",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(GoodbyeResponse)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
