// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: roundwire.proto

package roundwire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutPointPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Vout          uint32                 `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutPointPayload) Reset() {
	*x = OutPointPayload{}
	mi := &file_roundwire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutPointPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutPointPayload) ProtoMessage() {}

func (x *OutPointPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutPointPayload.ProtoReflect.Descriptor instead.
func (*OutPointPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{0}
}

func (x *OutPointPayload) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *OutPointPayload) GetVout() uint32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

type TxOutPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	PkScript      string                 `protobuf:"bytes,2,opt,name=pk_script,json=pkScript,proto3" json:"pk_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutPayload) Reset() {
	*x = TxOutPayload{}
	mi := &file_roundwire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutPayload) ProtoMessage() {}

func (x *TxOutPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutPayload.ProtoReflect.Descriptor instead.
func (*TxOutPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{1}
}

func (x *TxOutPayload) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxOutPayload) GetPkScript() string {
	if x != nil {
		return x.PkScript
	}
	return ""
}

type KeyDescriptorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyFamily     int32                  `protobuf:"varint,1,opt,name=key_family,json=keyFamily,proto3" json:"key_family,omitempty"`
	KeyIndex      uint32                 `protobuf:"varint,2,opt,name=key_index,json=keyIndex,proto3" json:"key_index,omitempty"`
	PubKeyHex     string                 `protobuf:"bytes,3,opt,name=pub_key_hex,json=pubKeyHex,proto3" json:"pub_key_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDescriptorPayload) Reset() {
	*x = KeyDescriptorPayload{}
	mi := &file_roundwire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDescriptorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDescriptorPayload) ProtoMessage() {}

func (x *KeyDescriptorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDescriptorPayload.ProtoReflect.Descriptor instead.
func (*KeyDescriptorPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{2}
}

func (x *KeyDescriptorPayload) GetKeyFamily() int32 {
	if x != nil {
		return x.KeyFamily
	}
	return 0
}

func (x *KeyDescriptorPayload) GetKeyIndex() uint32 {
	if x != nil {
		return x.KeyIndex
	}
	return 0
}

func (x *KeyDescriptorPayload) GetPubKeyHex() string {
	if x != nil {
		return x.PubKeyHex
	}
	return ""
}

type JoinRoundAuthPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageHex    string                 `protobuf:"bytes,1,opt,name=message_hex,json=messageHex,proto3" json:"message_hex,omitempty"`
	ValidFrom     uint32                 `protobuf:"varint,2,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil    uint32                 `protobuf:"varint,3,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	SignatureHex  string                 `protobuf:"bytes,4,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoundAuthPayload) Reset() {
	*x = JoinRoundAuthPayload{}
	mi := &file_roundwire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoundAuthPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoundAuthPayload) ProtoMessage() {}

func (x *JoinRoundAuthPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoundAuthPayload.ProtoReflect.Descriptor instead.
func (*JoinRoundAuthPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoundAuthPayload) GetMessageHex() string {
	if x != nil {
		return x.MessageHex
	}
	return ""
}

func (x *JoinRoundAuthPayload) GetValidFrom() uint32 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *JoinRoundAuthPayload) GetValidUntil() uint32 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *JoinRoundAuthPayload) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

type BoardingRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outpoint      *OutPointPayload       `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	ClientKey     string                 `protobuf:"bytes,2,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	OperatorKey   string                 `protobuf:"bytes,3,opt,name=operator_key,json=operatorKey,proto3" json:"operator_key,omitempty"`
	ExitDelay     uint32                 `protobuf:"varint,4,opt,name=exit_delay,json=exitDelay,proto3" json:"exit_delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardingRequestPayload) Reset() {
	*x = BoardingRequestPayload{}
	mi := &file_roundwire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardingRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardingRequestPayload) ProtoMessage() {}

func (x *BoardingRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardingRequestPayload.ProtoReflect.Descriptor instead.
func (*BoardingRequestPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{4}
}

func (x *BoardingRequestPayload) GetOutpoint() *OutPointPayload {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *BoardingRequestPayload) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *BoardingRequestPayload) GetOperatorKey() string {
	if x != nil {
		return x.OperatorKey
	}
	return ""
}

func (x *BoardingRequestPayload) GetExitDelay() uint32 {
	if x != nil {
		return x.ExitDelay
	}
	return 0
}

type VTXORequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PkScriptHex   string                 `protobuf:"bytes,2,opt,name=pk_script_hex,json=pkScriptHex,proto3" json:"pk_script_hex,omitempty"`
	Expiry        uint32                 `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	ClientKey     string                 `protobuf:"bytes,4,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	OperatorKey   string                 `protobuf:"bytes,5,opt,name=operator_key,json=operatorKey,proto3" json:"operator_key,omitempty"`
	SigningKey    *KeyDescriptorPayload  `protobuf:"bytes,6,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VTXORequestPayload) Reset() {
	*x = VTXORequestPayload{}
	mi := &file_roundwire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VTXORequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VTXORequestPayload) ProtoMessage() {}

func (x *VTXORequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VTXORequestPayload.ProtoReflect.Descriptor instead.
func (*VTXORequestPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{5}
}

func (x *VTXORequestPayload) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *VTXORequestPayload) GetPkScriptHex() string {
	if x != nil {
		return x.PkScriptHex
	}
	return ""
}

func (x *VTXORequestPayload) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *VTXORequestPayload) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *VTXORequestPayload) GetOperatorKey() string {
	if x != nil {
		return x.OperatorKey
	}
	return ""
}

func (x *VTXORequestPayload) GetSigningKey() *KeyDescriptorPayload {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

type ForfeitRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VtxoOutpoint  *OutPointPayload       `protobuf:"bytes,1,opt,name=vtxo_outpoint,json=vtxoOutpoint,proto3" json:"vtxo_outpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForfeitRequestPayload) Reset() {
	*x = ForfeitRequestPayload{}
	mi := &file_roundwire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForfeitRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForfeitRequestPayload) ProtoMessage() {}

func (x *ForfeitRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForfeitRequestPayload.ProtoReflect.Descriptor instead.
func (*ForfeitRequestPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{6}
}

func (x *ForfeitRequestPayload) GetVtxoOutpoint() *OutPointPayload {
	if x != nil {
		return x.VtxoOutpoint
	}
	return nil
}

type LeaveRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *TxOutPayload          `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequestPayload) Reset() {
	*x = LeaveRequestPayload{}
	mi := &file_roundwire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequestPayload) ProtoMessage() {}

func (x *LeaveRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequestPayload.ProtoReflect.Descriptor instead.
func (*LeaveRequestPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveRequestPayload) GetOutput() *TxOutPayload {
	if x != nil {
		return x.Output
	}
	return nil
}

type JoinRoundRequestPayload struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	RoundId          string                    `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Identifier       string                    `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	BoardingRequests []*BoardingRequestPayload `protobuf:"bytes,3,rep,name=boarding_requests,json=boardingRequests,proto3" json:"boarding_requests,omitempty"`
	VtxoRequests     []*VTXORequestPayload     `protobuf:"bytes,4,rep,name=vtxo_requests,json=vtxoRequests,proto3" json:"vtxo_requests,omitempty"`
	ForfeitRequests  []*ForfeitRequestPayload  `protobuf:"bytes,5,rep,name=forfeit_requests,json=forfeitRequests,proto3" json:"forfeit_requests,omitempty"`
	LeaveRequests    []*LeaveRequestPayload    `protobuf:"bytes,6,rep,name=leave_requests,json=leaveRequests,proto3" json:"leave_requests,omitempty"`
	Auth             *JoinRoundAuthPayload     `protobuf:"bytes,7,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinRoundRequestPayload) Reset() {
	*x = JoinRoundRequestPayload{}
	mi := &file_roundwire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoundRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoundRequestPayload) ProtoMessage() {}

func (x *JoinRoundRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoundRequestPayload.ProtoReflect.Descriptor instead.
func (*JoinRoundRequestPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoundRequestPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *JoinRoundRequestPayload) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *JoinRoundRequestPayload) GetBoardingRequests() []*BoardingRequestPayload {
	if x != nil {
		return x.BoardingRequests
	}
	return nil
}

func (x *JoinRoundRequestPayload) GetVtxoRequests() []*VTXORequestPayload {
	if x != nil {
		return x.VtxoRequests
	}
	return nil
}

func (x *JoinRoundRequestPayload) GetForfeitRequests() []*ForfeitRequestPayload {
	if x != nil {
		return x.ForfeitRequests
	}
	return nil
}

func (x *JoinRoundRequestPayload) GetLeaveRequests() []*LeaveRequestPayload {
	if x != nil {
		return x.LeaveRequests
	}
	return nil
}

func (x *JoinRoundRequestPayload) GetAuth() *JoinRoundAuthPayload {
	if x != nil {
		return x.Auth
	}
	return nil
}

type TxNonceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIdHex       string                 `protobuf:"bytes,1,opt,name=tx_id_hex,json=txIdHex,proto3" json:"tx_id_hex,omitempty"`
	NonceHex      string                 `protobuf:"bytes,2,opt,name=nonce_hex,json=nonceHex,proto3" json:"nonce_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxNonceEntry) Reset() {
	*x = TxNonceEntry{}
	mi := &file_roundwire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxNonceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxNonceEntry) ProtoMessage() {}

func (x *TxNonceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxNonceEntry.ProtoReflect.Descriptor instead.
func (*TxNonceEntry) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{9}
}

func (x *TxNonceEntry) GetTxIdHex() string {
	if x != nil {
		return x.TxIdHex
	}
	return ""
}

func (x *TxNonceEntry) GetNonceHex() string {
	if x != nil {
		return x.NonceHex
	}
	return ""
}

type SignerNonceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignerKeyHex  string                 `protobuf:"bytes,1,opt,name=signer_key_hex,json=signerKeyHex,proto3" json:"signer_key_hex,omitempty"`
	Nonces        []*TxNonceEntry        `protobuf:"bytes,2,rep,name=nonces,proto3" json:"nonces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignerNonceBundle) Reset() {
	*x = SignerNonceBundle{}
	mi := &file_roundwire_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerNonceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerNonceBundle) ProtoMessage() {}

func (x *SignerNonceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerNonceBundle.ProtoReflect.Descriptor instead.
func (*SignerNonceBundle) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{10}
}

func (x *SignerNonceBundle) GetSignerKeyHex() string {
	if x != nil {
		return x.SignerKeyHex
	}
	return ""
}

func (x *SignerNonceBundle) GetNonces() []*TxNonceEntry {
	if x != nil {
		return x.Nonces
	}
	return nil
}

type SubmitNoncesPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Entries       []*SignerNonceBundle   `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitNoncesPayload) Reset() {
	*x = SubmitNoncesPayload{}
	mi := &file_roundwire_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitNoncesPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitNoncesPayload) ProtoMessage() {}

func (x *SubmitNoncesPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitNoncesPayload.ProtoReflect.Descriptor instead.
func (*SubmitNoncesPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitNoncesPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SubmitNoncesPayload) GetEntries() []*SignerNonceBundle {
	if x != nil {
		return x.Entries
	}
	return nil
}

type TxSigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIdHex       string                 `protobuf:"bytes,1,opt,name=tx_id_hex,json=txIdHex,proto3" json:"tx_id_hex,omitempty"`
	SignatureHex  string                 `protobuf:"bytes,2,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSigEntry) Reset() {
	*x = TxSigEntry{}
	mi := &file_roundwire_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSigEntry) ProtoMessage() {}

func (x *TxSigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSigEntry.ProtoReflect.Descriptor instead.
func (*TxSigEntry) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{12}
}

func (x *TxSigEntry) GetTxIdHex() string {
	if x != nil {
		return x.TxIdHex
	}
	return ""
}

func (x *TxSigEntry) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

type SignerSigBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignerKeyHex  string                 `protobuf:"bytes,1,opt,name=signer_key_hex,json=signerKeyHex,proto3" json:"signer_key_hex,omitempty"`
	Signatures    []*TxSigEntry          `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignerSigBundle) Reset() {
	*x = SignerSigBundle{}
	mi := &file_roundwire_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerSigBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerSigBundle) ProtoMessage() {}

func (x *SignerSigBundle) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerSigBundle.ProtoReflect.Descriptor instead.
func (*SignerSigBundle) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{13}
}

func (x *SignerSigBundle) GetSignerKeyHex() string {
	if x != nil {
		return x.SignerKeyHex
	}
	return ""
}

func (x *SignerSigBundle) GetSignatures() []*TxSigEntry {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type SubmitPartialSigsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Entries       []*SignerSigBundle     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPartialSigsPayload) Reset() {
	*x = SubmitPartialSigsPayload{}
	mi := &file_roundwire_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPartialSigsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPartialSigsPayload) ProtoMessage() {}

func (x *SubmitPartialSigsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPartialSigsPayload.ProtoReflect.Descriptor instead.
func (*SubmitPartialSigsPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitPartialSigsPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SubmitPartialSigsPayload) GetEntries() []*SignerSigBundle {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BoardingInputSigPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputIndex    int32                  `protobuf:"varint,1,opt,name=input_index,json=inputIndex,proto3" json:"input_index,omitempty"`
	Outpoint      *OutPointPayload       `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	SignatureHex  string                 `protobuf:"bytes,3,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardingInputSigPayload) Reset() {
	*x = BoardingInputSigPayload{}
	mi := &file_roundwire_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardingInputSigPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardingInputSigPayload) ProtoMessage() {}

func (x *BoardingInputSigPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardingInputSigPayload.ProtoReflect.Descriptor instead.
func (*BoardingInputSigPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{15}
}

func (x *BoardingInputSigPayload) GetInputIndex() int32 {
	if x != nil {
		return x.InputIndex
	}
	return 0
}

func (x *BoardingInputSigPayload) GetOutpoint() *OutPointPayload {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *BoardingInputSigPayload) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

type SubmitForfeitSigsPayload struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RoundId       string                     `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Signatures    []*BoardingInputSigPayload `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitForfeitSigsPayload) Reset() {
	*x = SubmitForfeitSigsPayload{}
	mi := &file_roundwire_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitForfeitSigsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitForfeitSigsPayload) ProtoMessage() {}

func (x *SubmitForfeitSigsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitForfeitSigsPayload.ProtoReflect.Descriptor instead.
func (*SubmitForfeitSigsPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitForfeitSigsPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SubmitForfeitSigsPayload) GetSignatures() []*BoardingInputSigPayload {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type VTXOForfeitSigPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VtxoOutpoint  *OutPointPayload       `protobuf:"bytes,1,opt,name=vtxo_outpoint,json=vtxoOutpoint,proto3" json:"vtxo_outpoint,omitempty"`
	SignatureHex  string                 `protobuf:"bytes,2,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	UnsignedTxHex string                 `protobuf:"bytes,3,opt,name=unsigned_tx_hex,json=unsignedTxHex,proto3" json:"unsigned_tx_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VTXOForfeitSigPayload) Reset() {
	*x = VTXOForfeitSigPayload{}
	mi := &file_roundwire_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VTXOForfeitSigPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VTXOForfeitSigPayload) ProtoMessage() {}

func (x *VTXOForfeitSigPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VTXOForfeitSigPayload.ProtoReflect.Descriptor instead.
func (*VTXOForfeitSigPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{17}
}

func (x *VTXOForfeitSigPayload) GetVtxoOutpoint() *OutPointPayload {
	if x != nil {
		return x.VtxoOutpoint
	}
	return nil
}

func (x *VTXOForfeitSigPayload) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

func (x *VTXOForfeitSigPayload) GetUnsignedTxHex() string {
	if x != nil {
		return x.UnsignedTxHex
	}
	return ""
}

type SubmitVTXOForfeitSigsPayload struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RoundId       string                   `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Entries       []*VTXOForfeitSigPayload `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVTXOForfeitSigsPayload) Reset() {
	*x = SubmitVTXOForfeitSigsPayload{}
	mi := &file_roundwire_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVTXOForfeitSigsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVTXOForfeitSigsPayload) ProtoMessage() {}

func (x *SubmitVTXOForfeitSigsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVTXOForfeitSigsPayload.ProtoReflect.Descriptor instead.
func (*SubmitVTXOForfeitSigsPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{18}
}

func (x *SubmitVTXOForfeitSigsPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SubmitVTXOForfeitSigsPayload) GetEntries() []*VTXOForfeitSigPayload {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ClientErrorRespPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientErrorRespPayload) Reset() {
	*x = ClientErrorRespPayload{}
	mi := &file_roundwire_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientErrorRespPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientErrorRespPayload) ProtoMessage() {}

func (x *ClientErrorRespPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientErrorRespPayload.ProtoReflect.Descriptor instead.
func (*ClientErrorRespPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{19}
}

func (x *ClientErrorRespPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientSuccessRespPayload struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RoundId                   string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	AcceptedBoardingOutpoints []*OutPointPayload     `protobuf:"bytes,2,rep,name=accepted_boarding_outpoints,json=acceptedBoardingOutpoints,proto3" json:"accepted_boarding_outpoints,omitempty"`
	AcceptedVtxoOutpoints     []*OutPointPayload     `protobuf:"bytes,3,rep,name=accepted_vtxo_outpoints,json=acceptedVtxoOutpoints,proto3" json:"accepted_vtxo_outpoints,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ClientSuccessRespPayload) Reset() {
	*x = ClientSuccessRespPayload{}
	mi := &file_roundwire_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSuccessRespPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSuccessRespPayload) ProtoMessage() {}

func (x *ClientSuccessRespPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSuccessRespPayload.ProtoReflect.Descriptor instead.
func (*ClientSuccessRespPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{20}
}

func (x *ClientSuccessRespPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ClientSuccessRespPayload) GetAcceptedBoardingOutpoints() []*OutPointPayload {
	if x != nil {
		return x.AcceptedBoardingOutpoints
	}
	return nil
}

func (x *ClientSuccessRespPayload) GetAcceptedVtxoOutpoints() []*OutPointPayload {
	if x != nil {
		return x.AcceptedVtxoOutpoints
	}
	return nil
}

type ClientAwaitingInputSigsRespPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAwaitingInputSigsRespPayload) Reset() {
	*x = ClientAwaitingInputSigsRespPayload{}
	mi := &file_roundwire_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAwaitingInputSigsRespPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAwaitingInputSigsRespPayload) ProtoMessage() {}

func (x *ClientAwaitingInputSigsRespPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAwaitingInputSigsRespPayload.ProtoReflect.Descriptor instead.
func (*ClientAwaitingInputSigsRespPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{21}
}

func (x *ClientAwaitingInputSigsRespPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type ClientVTXOAggNoncesPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Nonces        []*TxNonceEntry        `protobuf:"bytes,2,rep,name=nonces,proto3" json:"nonces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientVTXOAggNoncesPayload) Reset() {
	*x = ClientVTXOAggNoncesPayload{}
	mi := &file_roundwire_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientVTXOAggNoncesPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVTXOAggNoncesPayload) ProtoMessage() {}

func (x *ClientVTXOAggNoncesPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVTXOAggNoncesPayload.ProtoReflect.Descriptor instead.
func (*ClientVTXOAggNoncesPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{22}
}

func (x *ClientVTXOAggNoncesPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ClientVTXOAggNoncesPayload) GetNonces() []*TxNonceEntry {
	if x != nil {
		return x.Nonces
	}
	return nil
}

type ClientVTXOAggSigsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Signatures    []*TxSigEntry          `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientVTXOAggSigsPayload) Reset() {
	*x = ClientVTXOAggSigsPayload{}
	mi := &file_roundwire_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientVTXOAggSigsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVTXOAggSigsPayload) ProtoMessage() {}

func (x *ClientVTXOAggSigsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVTXOAggSigsPayload.ProtoReflect.Descriptor instead.
func (*ClientVTXOAggSigsPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{23}
}

func (x *ClientVTXOAggSigsPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ClientVTXOAggSigsPayload) GetSignatures() []*TxSigEntry {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type NodePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *OutPointPayload       `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Outputs       []*TxOutPayload        `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	CoSigners     []string               `protobuf:"bytes,3,rep,name=co_signers,json=coSigners,proto3" json:"co_signers,omitempty"`
	Children      []*NodeChildPayload    `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	SignatureHex  string                 `protobuf:"bytes,6,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	FinalKeyHex   string                 `protobuf:"bytes,7,opt,name=final_key_hex,json=finalKeyHex,proto3" json:"final_key_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePayload) Reset() {
	*x = NodePayload{}
	mi := &file_roundwire_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePayload) ProtoMessage() {}

func (x *NodePayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePayload.ProtoReflect.Descriptor instead.
func (*NodePayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{24}
}

func (x *NodePayload) GetInput() *OutPointPayload {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *NodePayload) GetOutputs() []*TxOutPayload {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *NodePayload) GetCoSigners() []string {
	if x != nil {
		return x.CoSigners
	}
	return nil
}

func (x *NodePayload) GetChildren() []*NodeChildPayload {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *NodePayload) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NodePayload) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

func (x *NodePayload) GetFinalKeyHex() string {
	if x != nil {
		return x.FinalKeyHex
	}
	return ""
}

type NodeChildPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Node          *NodePayload           `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeChildPayload) Reset() {
	*x = NodeChildPayload{}
	mi := &file_roundwire_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeChildPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeChildPayload) ProtoMessage() {}

func (x *NodeChildPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeChildPayload.ProtoReflect.Descriptor instead.
func (*NodeChildPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{25}
}

func (x *NodeChildPayload) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *NodeChildPayload) GetNode() *NodePayload {
	if x != nil {
		return x.Node
	}
	return nil
}

type TreePayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Root               *NodePayload           `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	BatchOutpoint      *OutPointPayload       `protobuf:"bytes,2,opt,name=batch_outpoint,json=batchOutpoint,proto3" json:"batch_outpoint,omitempty"`
	BatchOutput        *TxOutPayload          `protobuf:"bytes,3,opt,name=batch_output,json=batchOutput,proto3" json:"batch_output,omitempty"`
	SweepTapscriptRoot string                 `protobuf:"bytes,4,opt,name=sweep_tapscript_root,json=sweepTapscriptRoot,proto3" json:"sweep_tapscript_root,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TreePayload) Reset() {
	*x = TreePayload{}
	mi := &file_roundwire_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreePayload) ProtoMessage() {}

func (x *TreePayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreePayload.ProtoReflect.Descriptor instead.
func (*TreePayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{26}
}

func (x *TreePayload) GetRoot() *NodePayload {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *TreePayload) GetBatchOutpoint() *OutPointPayload {
	if x != nil {
		return x.BatchOutpoint
	}
	return nil
}

func (x *TreePayload) GetBatchOutput() *TxOutPayload {
	if x != nil {
		return x.BatchOutput
	}
	return nil
}

func (x *TreePayload) GetSweepTapscriptRoot() string {
	if x != nil {
		return x.SweepTapscriptRoot
	}
	return ""
}

type TreePathPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputIndex   int32                  `protobuf:"varint,1,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	Tree          *TreePayload           `protobuf:"bytes,2,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreePathPayload) Reset() {
	*x = TreePathPayload{}
	mi := &file_roundwire_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreePathPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreePathPayload) ProtoMessage() {}

func (x *TreePathPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreePathPayload.ProtoReflect.Descriptor instead.
func (*TreePathPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{27}
}

func (x *TreePathPayload) GetOutputIndex() int32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *TreePathPayload) GetTree() *TreePayload {
	if x != nil {
		return x.Tree
	}
	return nil
}

type ConnectorLeafPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VtxoOutpoint  *OutPointPayload       `protobuf:"bytes,1,opt,name=vtxo_outpoint,json=vtxoOutpoint,proto3" json:"vtxo_outpoint,omitempty"`
	LeafOutpoint  *OutPointPayload       `protobuf:"bytes,2,opt,name=leaf_outpoint,json=leafOutpoint,proto3" json:"leaf_outpoint,omitempty"`
	LeafOutput    *TxOutPayload          `protobuf:"bytes,3,opt,name=leaf_output,json=leafOutput,proto3" json:"leaf_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorLeafPayload) Reset() {
	*x = ConnectorLeafPayload{}
	mi := &file_roundwire_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorLeafPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorLeafPayload) ProtoMessage() {}

func (x *ConnectorLeafPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorLeafPayload.ProtoReflect.Descriptor instead.
func (*ConnectorLeafPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{28}
}

func (x *ConnectorLeafPayload) GetVtxoOutpoint() *OutPointPayload {
	if x != nil {
		return x.VtxoOutpoint
	}
	return nil
}

func (x *ConnectorLeafPayload) GetLeafOutpoint() *OutPointPayload {
	if x != nil {
		return x.LeafOutpoint
	}
	return nil
}

func (x *ConnectorLeafPayload) GetLeafOutput() *TxOutPayload {
	if x != nil {
		return x.LeafOutput
	}
	return nil
}

type ClientBatchInfoPayload struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	RoundId         string                  `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	BatchPsbtHex    string                  `protobuf:"bytes,2,opt,name=batch_psbt_hex,json=batchPsbtHex,proto3" json:"batch_psbt_hex,omitempty"`
	VtxoTreePaths   []*TreePathPayload      `protobuf:"bytes,3,rep,name=vtxo_tree_paths,json=vtxoTreePaths,proto3" json:"vtxo_tree_paths,omitempty"`
	ConnectorLeaves []*ConnectorLeafPayload `protobuf:"bytes,4,rep,name=connector_leaves,json=connectorLeaves,proto3" json:"connector_leaves,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientBatchInfoPayload) Reset() {
	*x = ClientBatchInfoPayload{}
	mi := &file_roundwire_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientBatchInfoPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBatchInfoPayload) ProtoMessage() {}

func (x *ClientBatchInfoPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBatchInfoPayload.ProtoReflect.Descriptor instead.
func (*ClientBatchInfoPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{29}
}

func (x *ClientBatchInfoPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ClientBatchInfoPayload) GetBatchPsbtHex() string {
	if x != nil {
		return x.BatchPsbtHex
	}
	return ""
}

func (x *ClientBatchInfoPayload) GetVtxoTreePaths() []*TreePathPayload {
	if x != nil {
		return x.VtxoTreePaths
	}
	return nil
}

func (x *ClientBatchInfoPayload) GetConnectorLeaves() []*ConnectorLeafPayload {
	if x != nil {
		return x.ConnectorLeaves
	}
	return nil
}

type ClientRoundFailedRespPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRoundFailedRespPayload) Reset() {
	*x = ClientRoundFailedRespPayload{}
	mi := &file_roundwire_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRoundFailedRespPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRoundFailedRespPayload) ProtoMessage() {}

func (x *ClientRoundFailedRespPayload) ProtoReflect() protoreflect.Message {
	mi := &file_roundwire_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRoundFailedRespPayload.ProtoReflect.Descriptor instead.
func (*ClientRoundFailedRespPayload) Descriptor() ([]byte, []int) {
	return file_roundwire_proto_rawDescGZIP(), []int{30}
}

func (x *ClientRoundFailedRespPayload) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ClientRoundFailedRespPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_roundwire_proto protoreflect.FileDescriptor

const file_roundwire_proto_rawDesc = "" +
	"\n" +
	"\x0froundwire.proto\x12\troundwire\x1a\x1bgoogle/protobuf/empty.proto\":\n" +
	"\x0fOutPointPayload\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\rR\x04vout\"A\n" +
	"\fTxOutPayload\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1b\n" +
	"\tpk_script\x18\x02 \x01(\tR\bpkScript\"r\n" +
	"\x14KeyDescriptorPayload\x12\x1d\n" +
	"\n" +
	"key_family\x18\x01 \x01(\x05R\tkeyFamily\x12\x1b\n" +
	"\tkey_index\x18\x02 \x01(\rR\bkeyIndex\x12\x1e\n" +
	"\vpub_key_hex\x18\x03 \x01(\tR\tpubKeyHex\"\x9c\x01\n" +
	"\x14JoinRoundAuthPayload\x12\x1f\n" +
	"\vmessage_hex\x18\x01 \x01(\tR\n" +
	"messageHex\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x02 \x01(\rR\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x03 \x01(\rR\n" +
	"validUntil\x12#\n" +
	"\rsignature_hex\x18\x04 \x01(\tR\fsignatureHex\"\xb1\x01\n" +
	"\x16BoardingRequestPayload\x126\n" +
	"\boutpoint\x18\x01 \x01(\v2\x1a.roundwire.OutPointPayloadR\boutpoint\x12\x1d\n" +
	"\n" +
	"client_key\x18\x02 \x01(\tR\tclientKey\x12!\n" +
	"\foperator_key\x18\x03 \x01(\tR\voperatorKey\x12\x1d\n" +
	"\n" +
	"exit_delay\x18\x04 \x01(\rR\texitDelay\"\xec\x01\n" +
	"\x12VTXORequestPayload\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\"\n" +
	"\rpk_script_hex\x18\x02 \x01(\tR\vpkScriptHex\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\rR\x06expiry\x12\x1d\n" +
	"\n" +
	"client_key\x18\x04 \x01(\tR\tclientKey\x12!\n" +
	"\foperator_key\x18\x05 \x01(\tR\voperatorKey\x12@\n" +
	"\vsigning_key\x18\x06 \x01(\v2\x1f.roundwire.KeyDescriptorPayloadR\n" +
	"signingKey\"X\n" +
	"\x15ForfeitRequestPayload\x12?\n" +
	"\rvtxo_outpoint\x18\x01 \x01(\v2\x1a.roundwire.OutPointPayloadR\fvtxoOutpoint\"F\n" +
	"\x13LeaveRequestPayload\x12/\n" +
	"\x06output\x18\x01 \x01(\v2\x17.roundwire.TxOutPayloadR\x06output\"\xb1\x03\n" +
	"\x17JoinRoundRequestPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12N\n" +
	"\x11boarding_requests\x18\x03 \x03(\v2!.roundwire.BoardingRequestPayloadR\x10boardingRequests\x12B\n" +
	"\rvtxo_requests\x18\x04 \x03(\v2\x1d.roundwire.VTXORequestPayloadR\fvtxoRequests\x12K\n" +
	"\x10forfeit_requests\x18\x05 \x03(\v2 .roundwire.ForfeitRequestPayloadR\x0fforfeitRequests\x12E\n" +
	"\x0eleave_requests\x18\x06 \x03(\v2\x1e.roundwire.LeaveRequestPayloadR\rleaveRequests\x123\n" +
	"\x04auth\x18\a \x01(\v2\x1f.roundwire.JoinRoundAuthPayloadR\x04auth\"G\n" +
	"\fTxNonceEntry\x12\x1a\n" +
	"\ttx_id_hex\x18\x01 \x01(\tR\atxIdHex\x12\x1b\n" +
	"\tnonce_hex\x18\x02 \x01(\tR\bnonceHex\"j\n" +
	"\x11SignerNonceBundle\x12$\n" +
	"\x0esigner_key_hex\x18\x01 \x01(\tR\fsignerKeyHex\x12/\n" +
	"\x06nonces\x18\x02 \x03(\v2\x17.roundwire.TxNonceEntryR\x06nonces\"h\n" +
	"\x13SubmitNoncesPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x126\n" +
	"\aentries\x18\x02 \x03(\v2\x1c.roundwire.SignerNonceBundleR\aentries\"M\n" +
	"\n" +
	"TxSigEntry\x12\x1a\n" +
	"\ttx_id_hex\x18\x01 \x01(\tR\atxIdHex\x12#\n" +
	"\rsignature_hex\x18\x02 \x01(\tR\fsignatureHex\"n\n" +
	"\x0fSignerSigBundle\x12$\n" +
	"\x0esigner_key_hex\x18\x01 \x01(\tR\fsignerKeyHex\x125\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2\x15.roundwire.TxSigEntryR\n" +
	"signatures\"k\n" +
	"\x18SubmitPartialSigsPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x124\n" +
	"\aentries\x18\x02 \x03(\v2\x1a.roundwire.SignerSigBundleR\aentries\"\x97\x01\n" +
	"\x17BoardingInputSigPayload\x12\x1f\n" +
	"\vinput_index\x18\x01 \x01(\x05R\n" +
	"inputIndex\x126\n" +
	"\boutpoint\x18\x02 \x01(\v2\x1a.roundwire.OutPointPayloadR\boutpoint\x12#\n" +
	"\rsignature_hex\x18\x03 \x01(\tR\fsignatureHex\"y\n" +
	"\x18SubmitForfeitSigsPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12B\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2\".roundwire.BoardingInputSigPayloadR\n" +
	"signatures\"\xa5\x01\n" +
	"\x15VTXOForfeitSigPayload\x12?\n" +
	"\rvtxo_outpoint\x18\x01 \x01(\v2\x1a.roundwire.OutPointPayloadR\fvtxoOutpoint\x12#\n" +
	"\rsignature_hex\x18\x02 \x01(\tR\fsignatureHex\x12&\n" +
	"\x0funsigned_tx_hex\x18\x03 \x01(\tR\runsignedTxHex\"u\n" +
	"\x1cSubmitVTXOForfeitSigsPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12:\n" +
	"\aentries\x18\x02 \x03(\v2 .roundwire.VTXOForfeitSigPayloadR\aentries\".\n" +
	"\x16ClientErrorRespPayload\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xe5\x01\n" +
	"\x18ClientSuccessRespPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12Z\n" +
	"\x1baccepted_boarding_outpoints\x18\x02 \x03(\v2\x1a.roundwire.OutPointPayloadR\x19acceptedBoardingOutpoints\x12R\n" +
	"\x17accepted_vtxo_outpoints\x18\x03 \x03(\v2\x1a.roundwire.OutPointPayloadR\x15acceptedVtxoOutpoints\"?\n" +
	"\"ClientAwaitingInputSigsRespPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\"h\n" +
	"\x1aClientVTXOAggNoncesPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12/\n" +
	"\x06nonces\x18\x02 \x03(\v2\x17.roundwire.TxNonceEntryR\x06nonces\"l\n" +
	"\x18ClientVTXOAggSigsPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x125\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2\x15.roundwire.TxSigEntryR\n" +
	"signatures\"\xab\x02\n" +
	"\vNodePayload\x120\n" +
	"\x05input\x18\x01 \x01(\v2\x1a.roundwire.OutPointPayloadR\x05input\x121\n" +
	"\aoutputs\x18\x02 \x03(\v2\x17.roundwire.TxOutPayloadR\aoutputs\x12\x1d\n" +
	"\n" +
	"co_signers\x18\x03 \x03(\tR\tcoSigners\x127\n" +
	"\bchildren\x18\x04 \x03(\v2\x1b.roundwire.NodeChildPayloadR\bchildren\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12#\n" +
	"\rsignature_hex\x18\x06 \x01(\tR\fsignatureHex\x12\"\n" +
	"\rfinal_key_hex\x18\a \x01(\tR\vfinalKeyHex\"T\n" +
	"\x10NodeChildPayload\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12*\n" +
	"\x04node\x18\x02 \x01(\v2\x16.roundwire.NodePayloadR\x04node\"\xea\x01\n" +
	"\vTreePayload\x12*\n" +
	"\x04root\x18\x01 \x01(\v2\x16.roundwire.NodePayloadR\x04root\x12A\n" +
	"\x0ebatch_outpoint\x18\x02 \x01(\v2\x1a.roundwire.OutPointPayloadR\rbatchOutpoint\x12:\n" +
	"\fbatch_output\x18\x03 \x01(\v2\x17.roundwire.TxOutPayloadR\vbatchOutput\x120\n" +
	"\x14sweep_tapscript_root\x18\x04 \x01(\tR\x12sweepTapscriptRoot\"`\n" +
	"\x0fTreePathPayload\x12!\n" +
	"\foutput_index\x18\x01 \x01(\x05R\voutputIndex\x12*\n" +
	"\x04tree\x18\x02 \x01(\v2\x16.roundwire.TreePayloadR\x04tree\"\xd2\x01\n" +
	"\x14ConnectorLeafPayload\x12?\n" +
	"\rvtxo_outpoint\x18\x01 \x01(\v2\x1a.roundwire.OutPointPayloadR\fvtxoOutpoint\x12?\n" +
	"\rleaf_outpoint\x18\x02 \x01(\v2\x1a.roundwire.OutPointPayloadR\fleafOutpoint\x128\n" +
	"\vleaf_output\x18\x03 \x01(\v2\x17.roundwire.TxOutPayloadR\n" +
	"leafOutput\"\xe9\x01\n" +
	"\x16ClientBatchInfoPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12$\n" +
	"\x0ebatch_psbt_hex\x18\x02 \x01(\tR\fbatchPsbtHex\x12B\n" +
	"\x0fvtxo_tree_paths\x18\x03 \x03(\v2\x1a.roundwire.TreePathPayloadR\rvtxoTreePaths\x12J\n" +
	"\x10connector_leaves\x18\x04 \x03(\v2\x1f.roundwire.ConnectorLeafPayloadR\x0fconnectorLeaves\"Q\n" +
	"\x1cClientRoundFailedRespPayload\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x9b\b\n" +
	"\x13RoundMailboxService\x12N\n" +
	"\x10JoinRoundRequest\x12\".roundwire.JoinRoundRequestPayload\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x13SubmitNoncesRequest\x12\x1e.roundwire.SubmitNoncesPayload\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x17SubmitPartialSigRequest\x12#.roundwire.SubmitPartialSigsPayload\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x17SubmitForfeitSigRequest\x12#.roundwire.SubmitForfeitSigsPayload\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\x1cSubmitVTXOForfeitSigsRequest\x12'.roundwire.SubmitVTXOForfeitSigsPayload\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0fClientErrorResp\x12!.roundwire.ClientErrorRespPayload\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11ClientSuccessResp\x12#.roundwire.ClientSuccessRespPayload\x1a\x16.google.protobuf.Empty\x12d\n" +
	"\x1bClientAwaitingInputSigsResp\x12-.roundwire.ClientAwaitingInputSigsRespPayload\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x13ClientVTXOAggNonces\x12%.roundwire.ClientVTXOAggNoncesPayload\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11ClientVTXOAggSigs\x12#.roundwire.ClientVTXOAggSigsPayload\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0fClientBatchInfo\x12!.roundwire.ClientBatchInfoPayload\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x15ClientRoundFailedResp\x12'.roundwire.ClientRoundFailedRespPayload\x1a\x16.google.protobuf.EmptyB2Z0github.com/lightninglabs/darepo-client/roundwireb\x06proto3"

var (
	file_roundwire_proto_rawDescOnce sync.Once
	file_roundwire_proto_rawDescData []byte
)

func file_roundwire_proto_rawDescGZIP() []byte {
	file_roundwire_proto_rawDescOnce.Do(func() {
		file_roundwire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_roundwire_proto_rawDesc), len(file_roundwire_proto_rawDesc)))
	})
	return file_roundwire_proto_rawDescData
}

var file_roundwire_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_roundwire_proto_goTypes = []any{
	(*OutPointPayload)(nil),                    // 0: roundwire.OutPointPayload
	(*TxOutPayload)(nil),                       // 1: roundwire.TxOutPayload
	(*KeyDescriptorPayload)(nil),               // 2: roundwire.KeyDescriptorPayload
	(*JoinRoundAuthPayload)(nil),               // 3: roundwire.JoinRoundAuthPayload
	(*BoardingRequestPayload)(nil),             // 4: roundwire.BoardingRequestPayload
	(*VTXORequestPayload)(nil),                 // 5: roundwire.VTXORequestPayload
	(*ForfeitRequestPayload)(nil),              // 6: roundwire.ForfeitRequestPayload
	(*LeaveRequestPayload)(nil),                // 7: roundwire.LeaveRequestPayload
	(*JoinRoundRequestPayload)(nil),            // 8: roundwire.JoinRoundRequestPayload
	(*TxNonceEntry)(nil),                       // 9: roundwire.TxNonceEntry
	(*SignerNonceBundle)(nil),                  // 10: roundwire.SignerNonceBundle
	(*SubmitNoncesPayload)(nil),                // 11: roundwire.SubmitNoncesPayload
	(*TxSigEntry)(nil),                         // 12: roundwire.TxSigEntry
	(*SignerSigBundle)(nil),                    // 13: roundwire.SignerSigBundle
	(*SubmitPartialSigsPayload)(nil),           // 14: roundwire.SubmitPartialSigsPayload
	(*BoardingInputSigPayload)(nil),            // 15: roundwire.BoardingInputSigPayload
	(*SubmitForfeitSigsPayload)(nil),           // 16: roundwire.SubmitForfeitSigsPayload
	(*VTXOForfeitSigPayload)(nil),              // 17: roundwire.VTXOForfeitSigPayload
	(*SubmitVTXOForfeitSigsPayload)(nil),       // 18: roundwire.SubmitVTXOForfeitSigsPayload
	(*ClientErrorRespPayload)(nil),             // 19: roundwire.ClientErrorRespPayload
	(*ClientSuccessRespPayload)(nil),           // 20: roundwire.ClientSuccessRespPayload
	(*ClientAwaitingInputSigsRespPayload)(nil), // 21: roundwire.ClientAwaitingInputSigsRespPayload
	(*ClientVTXOAggNoncesPayload)(nil),         // 22: roundwire.ClientVTXOAggNoncesPayload
	(*ClientVTXOAggSigsPayload)(nil),           // 23: roundwire.ClientVTXOAggSigsPayload
	(*NodePayload)(nil),                        // 24: roundwire.NodePayload
	(*NodeChildPayload)(nil),                   // 25: roundwire.NodeChildPayload
	(*TreePayload)(nil),                        // 26: roundwire.TreePayload
	(*TreePathPayload)(nil),                    // 27: roundwire.TreePathPayload
	(*ConnectorLeafPayload)(nil),               // 28: roundwire.ConnectorLeafPayload
	(*ClientBatchInfoPayload)(nil),             // 29: roundwire.ClientBatchInfoPayload
	(*ClientRoundFailedRespPayload)(nil),       // 30: roundwire.ClientRoundFailedRespPayload
	(*emptypb.Empty)(nil),                      // 31: google.protobuf.Empty
}
var file_roundwire_proto_depIdxs = []int32{
	0,  // 0: roundwire.BoardingRequestPayload.outpoint:type_name -> roundwire.OutPointPayload
	2,  // 1: roundwire.VTXORequestPayload.signing_key:type_name -> roundwire.KeyDescriptorPayload
	0,  // 2: roundwire.ForfeitRequestPayload.vtxo_outpoint:type_name -> roundwire.OutPointPayload
	1,  // 3: roundwire.LeaveRequestPayload.output:type_name -> roundwire.TxOutPayload
	4,  // 4: roundwire.JoinRoundRequestPayload.boarding_requests:type_name -> roundwire.BoardingRequestPayload
	5,  // 5: roundwire.JoinRoundRequestPayload.vtxo_requests:type_name -> roundwire.VTXORequestPayload
	6,  // 6: roundwire.JoinRoundRequestPayload.forfeit_requests:type_name -> roundwire.ForfeitRequestPayload
	7,  // 7: roundwire.JoinRoundRequestPayload.leave_requests:type_name -> roundwire.LeaveRequestPayload
	3,  // 8: roundwire.JoinRoundRequestPayload.auth:type_name -> roundwire.JoinRoundAuthPayload
	9,  // 9: roundwire.SignerNonceBundle.nonces:type_name -> roundwire.TxNonceEntry
	10, // 10: roundwire.SubmitNoncesPayload.entries:type_name -> roundwire.SignerNonceBundle
	12, // 11: roundwire.SignerSigBundle.signatures:type_name -> roundwire.TxSigEntry
	13, // 12: roundwire.SubmitPartialSigsPayload.entries:type_name -> roundwire.SignerSigBundle
	0,  // 13: roundwire.BoardingInputSigPayload.outpoint:type_name -> roundwire.OutPointPayload
	15, // 14: roundwire.SubmitForfeitSigsPayload.signatures:type_name -> roundwire.BoardingInputSigPayload
	0,  // 15: roundwire.VTXOForfeitSigPayload.vtxo_outpoint:type_name -> roundwire.OutPointPayload
	17, // 16: roundwire.SubmitVTXOForfeitSigsPayload.entries:type_name -> roundwire.VTXOForfeitSigPayload
	0,  // 17: roundwire.ClientSuccessRespPayload.accepted_boarding_outpoints:type_name -> roundwire.OutPointPayload
	0,  // 18: roundwire.ClientSuccessRespPayload.accepted_vtxo_outpoints:type_name -> roundwire.OutPointPayload
	9,  // 19: roundwire.ClientVTXOAggNoncesPayload.nonces:type_name -> roundwire.TxNonceEntry
	12, // 20: roundwire.ClientVTXOAggSigsPayload.signatures:type_name -> roundwire.TxSigEntry
	0,  // 21: roundwire.NodePayload.input:type_name -> roundwire.OutPointPayload
	1,  // 22: roundwire.NodePayload.outputs:type_name -> roundwire.TxOutPayload
	25, // 23: roundwire.NodePayload.children:type_name -> roundwire.NodeChildPayload
	24, // 24: roundwire.NodeChildPayload.node:type_name -> roundwire.NodePayload
	24, // 25: roundwire.TreePayload.root:type_name -> roundwire.NodePayload
	0,  // 26: roundwire.TreePayload.batch_outpoint:type_name -> roundwire.OutPointPayload
	1,  // 27: roundwire.TreePayload.batch_output:type_name -> roundwire.TxOutPayload
	26, // 28: roundwire.TreePathPayload.tree:type_name -> roundwire.TreePayload
	0,  // 29: roundwire.ConnectorLeafPayload.vtxo_outpoint:type_name -> roundwire.OutPointPayload
	0,  // 30: roundwire.ConnectorLeafPayload.leaf_outpoint:type_name -> roundwire.OutPointPayload
	1,  // 31: roundwire.ConnectorLeafPayload.leaf_output:type_name -> roundwire.TxOutPayload
	27, // 32: roundwire.ClientBatchInfoPayload.vtxo_tree_paths:type_name -> roundwire.TreePathPayload
	28, // 33: roundwire.ClientBatchInfoPayload.connector_leaves:type_name -> roundwire.ConnectorLeafPayload
	8,  // 34: roundwire.RoundMailboxService.JoinRoundRequest:input_type -> roundwire.JoinRoundRequestPayload
	11, // 35: roundwire.RoundMailboxService.SubmitNoncesRequest:input_type -> roundwire.SubmitNoncesPayload
	14, // 36: roundwire.RoundMailboxService.SubmitPartialSigRequest:input_type -> roundwire.SubmitPartialSigsPayload
	16, // 37: roundwire.RoundMailboxService.SubmitForfeitSigRequest:input_type -> roundwire.SubmitForfeitSigsPayload
	18, // 38: roundwire.RoundMailboxService.SubmitVTXOForfeitSigsRequest:input_type -> roundwire.SubmitVTXOForfeitSigsPayload
	19, // 39: roundwire.RoundMailboxService.ClientErrorResp:input_type -> roundwire.ClientErrorRespPayload
	20, // 40: roundwire.RoundMailboxService.ClientSuccessResp:input_type -> roundwire.ClientSuccessRespPayload
	21, // 41: roundwire.RoundMailboxService.ClientAwaitingInputSigsResp:input_type -> roundwire.ClientAwaitingInputSigsRespPayload
	22, // 42: roundwire.RoundMailboxService.ClientVTXOAggNonces:input_type -> roundwire.ClientVTXOAggNoncesPayload
	23, // 43: roundwire.RoundMailboxService.ClientVTXOAggSigs:input_type -> roundwire.ClientVTXOAggSigsPayload
	29, // 44: roundwire.RoundMailboxService.ClientBatchInfo:input_type -> roundwire.ClientBatchInfoPayload
	30, // 45: roundwire.RoundMailboxService.ClientRoundFailedResp:input_type -> roundwire.ClientRoundFailedRespPayload
	31, // 46: roundwire.RoundMailboxService.JoinRoundRequest:output_type -> google.protobuf.Empty
	31, // 47: roundwire.RoundMailboxService.SubmitNoncesRequest:output_type -> google.protobuf.Empty
	31, // 48: roundwire.RoundMailboxService.SubmitPartialSigRequest:output_type -> google.protobuf.Empty
	31, // 49: roundwire.RoundMailboxService.SubmitForfeitSigRequest:output_type -> google.protobuf.Empty
	31, // 50: roundwire.RoundMailboxService.SubmitVTXOForfeitSigsRequest:output_type -> google.protobuf.Empty
	31, // 51: roundwire.RoundMailboxService.ClientErrorResp:output_type -> google.protobuf.Empty
	31, // 52: roundwire.RoundMailboxService.ClientSuccessResp:output_type -> google.protobuf.Empty
	31, // 53: roundwire.RoundMailboxService.ClientAwaitingInputSigsResp:output_type -> google.protobuf.Empty
	31, // 54: roundwire.RoundMailboxService.ClientVTXOAggNonces:output_type -> google.protobuf.Empty
	31, // 55: roundwire.RoundMailboxService.ClientVTXOAggSigs:output_type -> google.protobuf.Empty
	31, // 56: roundwire.RoundMailboxService.ClientBatchInfo:output_type -> google.protobuf.Empty
	31, // 57: roundwire.RoundMailboxService.ClientRoundFailedResp:output_type -> google.protobuf.Empty
	46, // [46:58] is the sub-list for method output_type
	34, // [34:46] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_roundwire_proto_init() }
func file_roundwire_proto_init() {
	if File_roundwire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_roundwire_proto_rawDesc), len(file_roundwire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roundwire_proto_goTypes,
		DependencyIndexes: file_roundwire_proto_depIdxs,
		MessageInfos:      file_roundwire_proto_msgTypes,
	}.Build()
	File_roundwire_proto = out.File
	file_roundwire_proto_goTypes = nil
	file_roundwire_proto_depIdxs = nil
}
