// Code generated by protoc-gen-mailboxrpc. DO NOT EDIT.

package roundwire

import (
	context "context"
	fmt "fmt"
	rpc "github.com/lightninglabs/darepo-client/mailbox/rpc"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// RoundMailboxServiceMailboxClient is a typed mailbox RPC client for RoundMailboxService.
type RoundMailboxServiceMailboxClient struct {
	// C is the underlying RPC-over-mailbox runtime client.
	C rpc.RPCClient
}

// NewRoundMailboxServiceMailboxClient creates a typed mailbox client.
func NewRoundMailboxServiceMailboxClient(c rpc.RPCClient) *RoundMailboxServiceMailboxClient {
	return &RoundMailboxServiceMailboxClient{
		C: c,
	}
}

// RoundMailboxServiceMailboxServer is the mailbox server interface for RoundMailboxService.
type RoundMailboxServiceMailboxServer interface {
	// JoinRoundRequest handles JoinRoundRequest.
	JoinRoundRequest(ctx context.Context, req *JoinRoundRequestPayload) (*emptypb.Empty, error)
	// SubmitNoncesRequest handles SubmitNoncesRequest.
	SubmitNoncesRequest(ctx context.Context, req *SubmitNoncesPayload) (*emptypb.Empty, error)
	// SubmitPartialSigRequest handles SubmitPartialSigRequest.
	SubmitPartialSigRequest(ctx context.Context, req *SubmitPartialSigsPayload) (*emptypb.Empty, error)
	// SubmitForfeitSigRequest handles SubmitForfeitSigRequest.
	SubmitForfeitSigRequest(ctx context.Context, req *SubmitForfeitSigsPayload) (*emptypb.Empty, error)
	// SubmitVTXOForfeitSigsRequest handles SubmitVTXOForfeitSigsRequest.
	SubmitVTXOForfeitSigsRequest(ctx context.Context, req *SubmitVTXOForfeitSigsPayload) (*emptypb.Empty, error)
	// ClientErrorResp handles ClientErrorResp.
	ClientErrorResp(ctx context.Context, req *ClientErrorRespPayload) (*emptypb.Empty, error)
	// ClientSuccessResp handles ClientSuccessResp.
	ClientSuccessResp(ctx context.Context, req *ClientSuccessRespPayload) (*emptypb.Empty, error)
	// ClientAwaitingInputSigsResp handles ClientAwaitingInputSigsResp.
	ClientAwaitingInputSigsResp(ctx context.Context, req *ClientAwaitingInputSigsRespPayload) (*emptypb.Empty, error)
	// ClientVTXOAggNonces handles ClientVTXOAggNonces.
	ClientVTXOAggNonces(ctx context.Context, req *ClientVTXOAggNoncesPayload) (*emptypb.Empty, error)
	// ClientVTXOAggSigs handles ClientVTXOAggSigs.
	ClientVTXOAggSigs(ctx context.Context, req *ClientVTXOAggSigsPayload) (*emptypb.Empty, error)
	// ClientBatchInfo handles ClientBatchInfo.
	ClientBatchInfo(ctx context.Context, req *ClientBatchInfoPayload) (*emptypb.Empty, error)
	// ClientRoundFailedResp handles ClientRoundFailedResp.
	ClientRoundFailedResp(ctx context.Context, req *ClientRoundFailedRespPayload) (*emptypb.Empty, error)
}

// RegisterRoundMailboxServiceMailboxServer registers handlers for RoundMailboxService.
func RegisterRoundMailboxServiceMailboxServer(r rpc.Router, impl RoundMailboxServiceMailboxServer) {
	r.Handle("roundwire.RoundMailboxService", "JoinRoundRequest", func() proto.Message {
		return &JoinRoundRequestPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*JoinRoundRequestPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.JoinRoundRequest(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "SubmitNoncesRequest", func() proto.Message {
		return &SubmitNoncesPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*SubmitNoncesPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SubmitNoncesRequest(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "SubmitPartialSigRequest", func() proto.Message {
		return &SubmitPartialSigsPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*SubmitPartialSigsPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SubmitPartialSigRequest(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "SubmitForfeitSigRequest", func() proto.Message {
		return &SubmitForfeitSigsPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*SubmitForfeitSigsPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SubmitForfeitSigRequest(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "SubmitVTXOForfeitSigsRequest", func() proto.Message {
		return &SubmitVTXOForfeitSigsPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*SubmitVTXOForfeitSigsPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.SubmitVTXOForfeitSigsRequest(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "ClientErrorResp", func() proto.Message {
		return &ClientErrorRespPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ClientErrorRespPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ClientErrorResp(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "ClientSuccessResp", func() proto.Message {
		return &ClientSuccessRespPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ClientSuccessRespPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ClientSuccessResp(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "ClientAwaitingInputSigsResp", func() proto.Message {
		return &ClientAwaitingInputSigsRespPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ClientAwaitingInputSigsRespPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ClientAwaitingInputSigsResp(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "ClientVTXOAggNonces", func() proto.Message {
		return &ClientVTXOAggNoncesPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ClientVTXOAggNoncesPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ClientVTXOAggNonces(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "ClientVTXOAggSigs", func() proto.Message {
		return &ClientVTXOAggSigsPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ClientVTXOAggSigsPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ClientVTXOAggSigs(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "ClientBatchInfo", func() proto.Message {
		return &ClientBatchInfoPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ClientBatchInfoPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ClientBatchInfo(ctx, req)
	})
	r.Handle("roundwire.RoundMailboxService", "ClientRoundFailedResp", func() proto.Message {
		return &ClientRoundFailedRespPayload{}
	}, func(ctx context.Context, msg proto.Message) (proto.Message, error) {
		req, ok := msg.(*ClientRoundFailedRespPayload)
		if !ok {
			return nil, fmt.Errorf("unexpected request type: %T", msg)
		}

		return impl.ClientRoundFailedResp(ctx, req)
	})
}

// JoinRoundRequest calls the JoinRoundRequest RPC.
func (c *RoundMailboxServiceMailboxClient) JoinRoundRequest(ctx context.Context, req *JoinRoundRequestPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "JoinRoundRequest",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SubmitNoncesRequest calls the SubmitNoncesRequest RPC.
func (c *RoundMailboxServiceMailboxClient) SubmitNoncesRequest(ctx context.Context, req *SubmitNoncesPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "SubmitNoncesRequest",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SubmitPartialSigRequest calls the SubmitPartialSigRequest RPC.
func (c *RoundMailboxServiceMailboxClient) SubmitPartialSigRequest(ctx context.Context, req *SubmitPartialSigsPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "SubmitPartialSigRequest",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SubmitForfeitSigRequest calls the SubmitForfeitSigRequest RPC.
func (c *RoundMailboxServiceMailboxClient) SubmitForfeitSigRequest(ctx context.Context, req *SubmitForfeitSigsPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "SubmitForfeitSigRequest",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SubmitVTXOForfeitSigsRequest calls the SubmitVTXOForfeitSigsRequest RPC.
func (c *RoundMailboxServiceMailboxClient) SubmitVTXOForfeitSigsRequest(ctx context.Context, req *SubmitVTXOForfeitSigsPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "SubmitVTXOForfeitSigsRequest",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ClientErrorResp calls the ClientErrorResp RPC.
func (c *RoundMailboxServiceMailboxClient) ClientErrorResp(ctx context.Context, req *ClientErrorRespPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "ClientErrorResp",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ClientSuccessResp calls the ClientSuccessResp RPC.
func (c *RoundMailboxServiceMailboxClient) ClientSuccessResp(ctx context.Context, req *ClientSuccessRespPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "ClientSuccessResp",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ClientAwaitingInputSigsResp calls the ClientAwaitingInputSigsResp RPC.
func (c *RoundMailboxServiceMailboxClient) ClientAwaitingInputSigsResp(ctx context.Context, req *ClientAwaitingInputSigsRespPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "ClientAwaitingInputSigsResp",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ClientVTXOAggNonces calls the ClientVTXOAggNonces RPC.
func (c *RoundMailboxServiceMailboxClient) ClientVTXOAggNonces(ctx context.Context, req *ClientVTXOAggNoncesPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "ClientVTXOAggNonces",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ClientVTXOAggSigs calls the ClientVTXOAggSigs RPC.
func (c *RoundMailboxServiceMailboxClient) ClientVTXOAggSigs(ctx context.Context, req *ClientVTXOAggSigsPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "ClientVTXOAggSigs",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ClientBatchInfo calls the ClientBatchInfo RPC.
func (c *RoundMailboxServiceMailboxClient) ClientBatchInfo(ctx context.Context, req *ClientBatchInfoPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "ClientBatchInfo",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ClientRoundFailedResp calls the ClientRoundFailedResp RPC.
func (c *RoundMailboxServiceMailboxClient) ClientRoundFailedResp(ctx context.Context, req *ClientRoundFailedRespPayload, opts ...rpc.RPCOptions) (*emptypb.Empty, error) {
	var opt rpc.RPCOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	result, err := c.C.SendRPC(ctx, rpc.ServiceMethod{
		Service: "roundwire.RoundMailboxService",
		Method:  "ClientRoundFailedResp",
	}, req, opt)
	if err != nil {
		return nil, err
	}

	resp := new(emptypb.Empty)
	if err := c.C.AwaitRPC(ctx, result.CorrelationID, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
